var ca_del = {
"NRM_DEL_M_CSL_UNI": "l", "NRM_DEL_M_ASO_UNI": "r", "NRM_DEL_M_VAR_UNI": "m", "NRM_DEL_M_COA_UNI": "n", "NRM_DEL_U_CSL_UNI": "t", "NRM_DEL_U_ASO_UNI": "k", "NRM_DEL_U_VAR_UNI": "p", "NRM_DEL_U_COA_UNI": "q", "NRM_DEL_N_CSL_UNI": "ţ", "NRM_DEL_N_ASO_UNI": "x", "NRM_DEL_N_VAR_UNI": "f", "NRM_DEL_N_COA_UNI": "xh", "NRM_DEL_A_CSL_UNI": "c", "NRM_DEL_A_ASO_UNI": "č", "NRM_DEL_A_VAR_UNI": "ż", "NRM_DEL_A_COA_UNI": "j", "NRM_DEL_M_CSL_DPX": "ll", "NRM_DEL_M_ASO_DPX": "rr", "NRM_DEL_M_VAR_DPX": "mm", "NRM_DEL_M_COA_DPX": "nn", "NRM_DEL_U_CSL_DPX": "ļt", "NRM_DEL_U_ASO_DPX": "ļk", "NRM_DEL_U_VAR_DPX": "ļp", "NRM_DEL_U_COA_DPX": "ļq", "NRM_DEL_N_CSL_DPX": "ţţ", "NRM_DEL_N_ASO_DPX": "xx", "NRM_DEL_N_VAR_DPX": "ff", "NRM_DEL_N_COA_DPX": "xxh", "NRM_DEL_A_CSL_DPX": "cc", "NRM_DEL_A_ASO_DPX": "čč", "NRM_DEL_A_VAR_DPX": "żż", "NRM_DEL_A_COA_DPX": "jj", "NRM_DEL_M_CSL_DCT": "tļ", "NRM_DEL_M_ASO_DCT": "lļ", "NRM_DEL_M_VAR_DCT": "lm", "NRM_DEL_M_COA_DCT": "ln", "NRM_DEL_U_CSL_DCT": "lt", "NRM_DEL_U_ASO_DCT": "lk", "NRM_DEL_U_VAR_DCT": "lp", "NRM_DEL_U_COA_DCT": "lq", "NRM_DEL_N_CSL_DCT": "lţ", "NRM_DEL_N_ASO_DCT": "lx", "NRM_DEL_N_VAR_DCT": "lf", "NRM_DEL_N_COA_DCT": "lxh", "NRM_DEL_A_CSL_DCT": "lc", "NRM_DEL_A_ASO_DCT": "lč", "NRM_DEL_A_VAR_DCT": "lż", "NRM_DEL_A_COA_DCT": "lj", "NRM_DEL_M_CSL_AGG": "ļ", "NRM_DEL_M_ASO_AGG": "rl", "NRM_DEL_M_VAR_AGG": "rm", "NRM_DEL_M_COA_AGG": "rn", "NRM_DEL_U_CSL_AGG": "rt", "NRM_DEL_U_ASO_AGG": "rk", "NRM_DEL_U_VAR_AGG": "rp", "NRM_DEL_U_COA_AGG": "rq", "NRM_DEL_N_CSL_AGG": "rţ", "NRM_DEL_N_ASO_AGG": "rx", "NRM_DEL_N_VAR_AGG": "rf", "NRM_DEL_N_COA_AGG": "rxh", "NRM_DEL_A_CSL_AGG": "rc", "NRM_DEL_A_ASO_AGG": "rč", "NRM_DEL_A_VAR_AGG": "rż", "NRM_DEL_A_COA_AGG": "rj", "NRM_DEL_M_CSL_SEG": "ļļ", "NRM_DEL_M_ASO_SEG": "rļ", "NRM_DEL_M_VAR_SEG": "mļ", "NRM_DEL_M_COA_SEG": "nļ", "NRM_DEL_U_CSL_SEG": "nt", "NRM_DEL_U_ASO_SEG": "ňk", "NRM_DEL_U_VAR_SEG": "mp", "NRM_DEL_U_COA_SEG": "ňq", "NRM_DEL_N_CSL_SEG": "nţ", "NRM_DEL_N_ASO_SEG": "ňx", "NRM_DEL_N_VAR_SEG": "mf", "NRM_DEL_N_COA_SEG": "ňxh", "NRM_DEL_A_CSL_SEG": "ns", "NRM_DEL_A_ASO_SEG": "nš", "NRM_DEL_A_VAR_SEG": "nz", "NRM_DEL_A_COA_SEG": "nž", "NRM_DEL_M_CSL_CPN": "řļ", "NRM_DEL_M_ASO_CPN": "řl", "NRM_DEL_M_VAR_CPN": "řm", "NRM_DEL_M_COA_CPN": "řn", "NRM_DEL_U_CSL_CPN": "řt", "NRM_DEL_U_ASO_CPN": "řk", "NRM_DEL_U_VAR_CPN": "řp", "NRM_DEL_U_COA_CPN": "řq", "NRM_DEL_N_CSL_CPN": "řţ", "NRM_DEL_N_ASO_CPN": "mx", "NRM_DEL_N_VAR_CPN": "řf", "NRM_DEL_N_COA_CPN": "mxh", "NRM_DEL_A_CSL_CPN": "řc", "NRM_DEL_A_ASO_CPN": "řč", "NRM_DEL_A_VAR_CPN": "řż", "NRM_DEL_A_COA_CPN": "řj", "NRM_DEL_M_CSL_COH": "sk", "NRM_DEL_M_ASO_COH": "st", "NRM_DEL_M_VAR_COH": "sp", "NRM_DEL_M_COA_COH": "sq", "NRM_DEL_U_CSL_COH": "ňt", "NRM_DEL_U_ASO_COH": "kt", "NRM_DEL_U_VAR_COH": "pt", "NRM_DEL_U_COA_COH": "qt", "NRM_DEL_N_CSL_COH": "sţ", "NRM_DEL_N_ASO_COH": "sx", "NRM_DEL_N_VAR_COH": "sf", "NRM_DEL_N_COA_COH": "sxh", "NRM_DEL_A_CSL_COH": "sc", "NRM_DEL_A_ASO_COH": "šč", "NRM_DEL_A_VAR_COH": "ţf", "NRM_DEL_A_COA_COH": "fţ", "NRM_DEL_M_CSL_CST": "šk", "NRM_DEL_M_ASO_CST": "št", "NRM_DEL_M_VAR_CST": "šp", "NRM_DEL_M_COA_CST": "šq", "NRM_DEL_U_CSL_CST": "ňd", "NRM_DEL_U_ASO_CST": "xt", "NRM_DEL_U_VAR_CST": "ft", "NRM_DEL_U_COA_CST": "xht", "NRM_DEL_N_CSL_CST": "šţ", "NRM_DEL_N_ASO_CST": "šx", "NRM_DEL_N_VAR_CST": "šf", "NRM_DEL_N_COA_CST": "šxh", "NRM_DEL_A_CSL_CST": "fk", "NRM_DEL_A_ASO_CST": "ţk", "NRM_DEL_A_VAR_CST": "ţs", "NRM_DEL_A_COA_CST": "ţš", "NRM_DEL_M_CSL_MLT": "kţ", "NRM_DEL_M_ASO_MLT": "kç", "NRM_DEL_M_VAR_MLT": "pţ", "NRM_DEL_M_COA_MLT": "qţ", "NRM_DEL_U_CSL_MLT": "çt", "NRM_DEL_U_ASO_MLT": "çk", "NRM_DEL_U_VAR_MLT": "çp", "NRM_DEL_U_COA_MLT": "çq", "NRM_DEL_N_CSL_MLT": "tf", "NRM_DEL_N_ASO_MLT": "kf", "NRM_DEL_N_VAR_MLT": "pf", "NRM_DEL_N_COA_MLT": "qf", "NRM_DEL_A_CSL_MLT": "fq", "NRM_DEL_A_ASO_MLT": "ţq", "NRM_DEL_A_VAR_MLT": "ţc", "NRM_DEL_A_COA_MLT": "ţč", "RPV_DEL_M_CSL_UNI": "tt", "RPV_DEL_M_ASO_UNI": "kk", "RPV_DEL_M_VAR_UNI": "pp", "RPV_DEL_M_COA_UNI": "qq", "RPV_DEL_U_CSL_UNI": "dd", "RPV_DEL_U_ASO_UNI": "gg", "RPV_DEL_U_VAR_UNI": "bb", "RPV_DEL_U_COA_UNI": "cf", "RPV_DEL_N_CSL_UNI": "ţw", "RPV_DEL_N_ASO_UNI": "xw", "RPV_DEL_N_VAR_UNI": "fw", "RPV_DEL_N_COA_UNI": "xhw", "RPV_DEL_A_CSL_UNI": "sw", "RPV_DEL_A_ASO_UNI": "šw", "RPV_DEL_A_VAR_UNI": "zw", "RPV_DEL_A_COA_UNI": "žw", "RPV_DEL_M_CSL_DPX": "tt'", "RPV_DEL_M_ASO_DPX": "kk'", "RPV_DEL_M_VAR_DPX": "pp'", "RPV_DEL_M_COA_DPX": "qq'", "RPV_DEL_U_CSL_DPX": "nçw", "RPV_DEL_U_ASO_DPX": "ňçw", "RPV_DEL_U_VAR_DPX": "mçw", "RPV_DEL_U_COA_DPX": "čf", "RPV_DEL_N_CSL_DPX": "dhw", "RPV_DEL_N_ASO_DPX": "ňw", "RPV_DEL_N_VAR_DPX": "vw", "RPV_DEL_N_COA_DPX": "çw", "RPV_DEL_A_CSL_DPX": "cw", "RPV_DEL_A_ASO_DPX": "čw", "RPV_DEL_A_VAR_DPX": "żw", "RPV_DEL_A_COA_DPX": "jw", "RPV_DEL_M_CSL_DCT": "tth", "RPV_DEL_M_ASO_DCT": "kkh", "RPV_DEL_M_VAR_DCT": "pph", "RPV_DEL_M_COA_DCT": "qqh", "RPV_DEL_U_CSL_DCT": "pçw", "RPV_DEL_U_ASO_DCT": "kfw", "RPV_DEL_U_VAR_DCT": "pfw", "RPV_DEL_U_COA_DCT": "qfw", "RPV_DEL_N_CSL_DCT": "lţw", "RPV_DEL_N_ASO_DCT": "lxw", "RPV_DEL_N_VAR_DCT": "lfw", "RPV_DEL_N_COA_DCT": "lxhw", "RPV_DEL_A_CSL_DCT": "lsw", "RPV_DEL_A_ASO_DCT": "lšw", "RPV_DEL_A_VAR_DCT": "lzw", "RPV_DEL_A_COA_DCT": "lžw", "RPV_DEL_M_CSL_AGG": "lpt'", "RPV_DEL_M_ASO_AGG": "lkt'", "RPV_DEL_M_VAR_AGG": "lpk'", "RPV_DEL_M_COA_AGG": "ltk'", "RPV_DEL_U_CSL_AGG": "lft'", "RPV_DEL_U_ASO_AGG": "lxt'", "RPV_DEL_U_VAR_AGG": "lfk'", "RPV_DEL_U_COA_AGG": "lţk'", "RPV_DEL_N_CSL_AGG": "rţw", "RPV_DEL_N_ASO_AGG": "rxw", "RPV_DEL_N_VAR_AGG": "rfw", "RPV_DEL_N_COA_AGG": "rxhw", "RPV_DEL_A_CSL_AGG": "rsw", "RPV_DEL_A_ASO_AGG": "ršw", "RPV_DEL_A_VAR_AGG": "rzw", "RPV_DEL_A_COA_AGG": "ržw", "RPV_DEL_M_CSL_SEG": "rpt'", "RPV_DEL_M_ASO_SEG": "rkt'", "RPV_DEL_M_VAR_SEG": "rpk'", "RPV_DEL_M_COA_SEG": "rtk'", "RPV_DEL_U_CSL_SEG": "rft'", "RPV_DEL_U_ASO_SEG": "rxt'", "RPV_DEL_U_VAR_SEG": "rfk'", "RPV_DEL_U_COA_SEG": "rţk'", "RPV_DEL_N_CSL_SEG": "mţw", "RPV_DEL_N_ASO_SEG": "mxw", "RPV_DEL_N_VAR_SEG": "ňfw", "RPV_DEL_N_COA_SEG": "mxhw", "RPV_DEL_A_CSL_SEG": "msw", "RPV_DEL_A_ASO_SEG": "mšw", "RPV_DEL_A_VAR_SEG": "mzw", "RPV_DEL_A_COA_SEG": "mžw", "RPV_DEL_M_CSL_CPN": "řpt'", "RPV_DEL_M_ASO_CPN": "řkt'", "RPV_DEL_M_VAR_CPN": "řpk'", "RPV_DEL_M_COA_CPN": "řtk'", "RPV_DEL_U_CSL_CPN": "řft'", "RPV_DEL_U_ASO_CPN": "řxt'", "RPV_DEL_U_VAR_CPN": "řfk'", "RPV_DEL_U_COA_CPN": "řţk'", "RPV_DEL_N_CSL_CPN": "řţw", "RPV_DEL_N_ASO_CPN": "řxw", "RPV_DEL_N_VAR_CPN": "řfw", "RPV_DEL_N_COA_CPN": "tçw", "RPV_DEL_A_CSL_CPN": "řsw", "RPV_DEL_A_ASO_CPN": "řšw", "RPV_DEL_A_VAR_CPN": "řzw", "RPV_DEL_A_COA_CPN": "řžw", "RPV_DEL_M_CSL_COH": "lpth", "RPV_DEL_M_ASO_COH": "lkth", "RPV_DEL_M_VAR_COH": "lpkh", "RPV_DEL_M_COA_COH": "ltkh", "RPV_DEL_U_CSL_COH": "lfth", "RPV_DEL_U_ASO_COH": "lxth", "RPV_DEL_U_VAR_COH": "lfkh", "RPV_DEL_U_COA_COH": "lţkh", "RPV_DEL_N_CSL_COH": "nţw", "RPV_DEL_N_ASO_COH": "ňxw", "RPV_DEL_N_VAR_COH": "mfw", "RPV_DEL_N_COA_COH": "ňxhw", "RPV_DEL_A_CSL_COH": "nsw", "RPV_DEL_A_ASO_COH": "nšw", "RPV_DEL_A_VAR_COH": "nzw", "RPV_DEL_A_COA_COH": "nžw", "RPV_DEL_M_CSL_CST": "rpth", "RPV_DEL_M_ASO_CST": "rkth", "RPV_DEL_M_VAR_CST": "rpkh", "RPV_DEL_M_COA_CST": "rtkh", "RPV_DEL_U_CSL_CST": "rfth", "RPV_DEL_U_ASO_CST": "rxth", "RPV_DEL_U_VAR_CST": "rfkh", "RPV_DEL_U_COA_CST": "rţkh", "RPV_DEL_N_CSL_CST": "ldhw", "RPV_DEL_N_ASO_CST": "lňw", "RPV_DEL_N_VAR_CST": "lvw", "RPV_DEL_N_COA_CST": "lçw", "RPV_DEL_A_CSL_CST": "ňsw", "RPV_DEL_A_ASO_CST": "ňšw", "RPV_DEL_A_VAR_CST": "ňzw", "RPV_DEL_A_COA_CST": "ňžw", "RPV_DEL_M_CSL_MLT": "řpth", "RPV_DEL_M_ASO_MLT": "řkth", "RPV_DEL_M_VAR_MLT": "řpkh", "RPV_DEL_M_COA_MLT": "řtkh", "RPV_DEL_U_CSL_MLT": "řfth", "RPV_DEL_U_ASO_MLT": "řxth", "RPV_DEL_U_VAR_MLT": "řfkh", "RPV_DEL_U_COA_MLT": "řţkh", "RPV_DEL_N_CSL_MLT": "rdhw", "RPV_DEL_N_ASO_MLT": "rňw", "RPV_DEL_N_VAR_MLT": "rvw", "RPV_DEL_N_COA_MLT": "rçw", "RPV_DEL_A_CSL_MLT": "ssw", "RPV_DEL_A_ASO_MLT": "ššw", "RPV_DEL_A_VAR_MLT": "zzw", "RPV_DEL_A_COA_MLT": "žžw" }

var cs = {
"(none)":"n-n",
"RETROSPECTIVE":"n-nr",
"PROSPECTIVE":"m-mr",
"HABITUAL":"l-lr",
"PROGRESSIVE":"r-rn",
"IMMINENT (about to, on the verge of)":"ň-ňr",
"PRECESSIVE (just)":"n-nw",
"REGULATIVE (engaged in, involved in)":"m-mw",
"EXPERIENTIAL (ever)":"l-lw",
"RESUMPTIVE (resume, start again)":"r-rw",
"CESSATIVE (stop, cease)":"ň-ňw",
"RECESSATIVE (stop again)":"n-ny",
"PAUSAL (take a break, pause)":"m-my",
"REGRESSIVE (return after long break)":"l-ly",
"PRECLUSIVE (all in one go, without stopping)":"r-ry",
"CONTINUATIVE (keep on, still, stay, yet)":"n-ns",
"INCESSATIVE (on and on)":"m-ms",
"PREEMPTIVE (for once, at last, finally)":"ň-ňs",
"CLIMACTIC (once and for all, for the last time)":"l-ls",
"PROTRACTIVE (for a long time)":"r-rs",
"TEMPORARY (for the time being, for now)":"n-nš ",
"MOTIVE (be off ... ing, go off to ...)":"m-mš ",
"CONSEQUENTIAL (go ahead and, anyway)":"ň-ňš ",
"SEQUENTIAL":"l-lš ",
"EXPEDITIVE (hastily, in a hurry)":"r-rš",
"DISCLUSIVE (turn out to be)":"n-nļ",
"CONCLUSIVE (end up ...ing, up to the point where...)":"l-lm",
"CULMINATIVE (eventually, get to the point where...)":"r-rm",
"INTERMEDIATIVE (at some point, somewhere along the way)":"l-ln",
"TARDATIVE (lesseningly, dwindingly, peter out)":"l-nw",
"TRANSITIONAL (take up, start to)":"r-nw",
"INTERCOMMUTATIVE (to do something back to someone)":"l-mw",
"CONSUMPTIVE (spend one's time, all-consuming action)":"r-mw"

}

var vs = {
"(none)":"a",
"RETROSPECTIVE":"u",
"PROSPECTIVE":"e",
"HABITUAL":"o",
"PROGRESSIVE":"i",
"IMMINENT":"ö",
"PRECESSIVE":"î",
"REGULATIVE":"â",
"EXPERIENTIAL":"ê",
"RESUMPTIVE":"ô",
"CESSATIVE":"ü",
"RECESSATIVE":"ai",
"PAUSAL":"ei",
"REGRESSIVE":"ui",
"PRECLUSIVE":"oi",
"CONTINUATIVE":"iu",
"INCESSATIVE":"au",
"PREEMPTIVE":"eu",
"CLIMACTIC":"ou",
"PROTRACTIVE":"ae",
"TEMPORARY":"ia",
"MOTIVE":"ie",
"CONSEQUENTIAL":"io",
"SEQUENTIAL":"iù",
"EXPEDITIVE":"iö",
"DISCLUSIVE":"ea",
"CONCLUSIVE":"oa",
"CULMINATIVE":"eö",
"INTERMEDIATIVE":"öi",
"TARDATIVE":"öu",
"TRANSITIONAL":"eo",
"INTERCOMMUTATIVE":"ëi",
"CONSUMPTIVE":"ëu"
}

var vc_aso = {
"PARTATIVE":"ia",
"CONTRASTIVE":"ie",
"COMPOSITIVE":"io",
"PREDICATIVE":"iö",
"MEDIATIVE":"a'",
"APPLICATIVE":"u'",
"PURPOSIVE":"e'",
"CONSIDERATIVE":"o'",
"ESSIVE":"ea",
"ASSIMILATIVE":"eo",
"FUNCTIVE":"eö",
"TRANSFORMATIVE":"oa",
"REFERENTIAL":"oe",
"CLASSIFICATIVE":"öa",
"CONDUCTIVE":"öe",
"INTERDEPENDENT":"üa",
"BENEFACTIVE":"üe",
"TRANSPOSITIVE":"üo",
"COMMUTATIVE":"au",
"COMITATIVE":"eu",
"CONJUNCTIVE":"iu",
"UTILITATIVE":"ou",
"ABESSIVE":"ëu",
"CONVERSIVE":"öu",
"CORRELATIVE":"ai'",
"DEPENDENT":"ui'",
"PROVISIONAL":"ei'",
"POSTULATIVE":"oi'",
"CONCESSIVE":"au'",
"EXCEPTIVE":"iu'",
"AVERSIVE":"eu'",
"COMPARATIVE":"ou'"
}

var vc = {
"OBLIQUE":"a",
"INDUCIVE":"u",
"ABSOLUTIVE":"e",
"ERGATIVE":"o",
"EFFECTUATIVE":"ö",
"AFFECTIVE":"i",
"DATIVE":"ü",
"INSTRUMENTAL":"ai",
"ACTIVATIVE":"ei",
"DERIVATIVE":"ui",
"SITUATIVE":"oi",
"POSSESSIVE":"â",
"PROPRIETIVE":"î",
"GENITIVE":"ê",
"ATTRIBUTIVE":"ô",
"PRODUCTIVE":"ëi",
"INTERPRETATIVE":"öi",
"ORIGINATIVE":"ae",
"PARTATIVE":"ia",
"CONTRASTIVE":"ie",
"COMPOSITIVE":"io",
"PREDICATIVE":"iö",
"MEDIATIVE":"a'",
"APPLICATIVE":"u'",
"PURPOSIVE":"e'",
"CONSIDERATIVE":"o'",
"ESSIVE":"ea",
"ASSIMILATIVE":"eo",
"FUNCTIVE":"eö",
"TRANSFORMATIVE":"oa",
"REFERENTIAL":"oe",
"CLASSIFICATIVE":"öa",
"CONDUCTIVE":"öe",
"INTERDEPENDENT":"üa",
"BENEFACTIVE":"üe",
"TRANSPOSITIVE":"üo",
"COMMUTATIVE":"au",
"COMITATIVE":"eu",
"CONJUNCTIVE":"iu",
"UTILITATIVE":"ou",
"ABESSIVE":"ëu",
"CONVERSIVE":"öu",
"CORRELATIVE":"ai'",
"DEPENDENT":"ui'",
"PROVISIONAL":"ei'",
"POSTULATIVE":"oi'",
"CONCESSIVE":"au'",
"EXCEPTIVE":"iu'",
"AVERSIVE":"eu'",
"COMPARATIVE":"ou'",
"SIMULTANEITIVE":"a'a",
"ASSESSIVE":"e'a",
"CONCURSIVE":"i'a",
"ACCESSIVE":"o'a",
"DIFFUSIVE":"u'a",
"PERIODIC":"ö'a",
"PROLAPSIVE":"ü'",
"PRECURSIVE":"ai'a",
"POSTCURSIVE":"ei'a",
"ELAPSIVE":"ui'a",
"ALLAPSIVE":"oi'a",
"INTERPOLATIVE":"ëi'a",
"EPISODIC":"au'a",
"PROLIMITIVE":"eu'a",
"LIMITATIVE":"iu'a",
"LOCATIVE":"â'a",
"ORIENTATIVE":"ê'a",
"PROCURSIVE":"ô'a",
"ALLATIVE":"î'a",
"ABLATIVE":"ëu'a",
"NAVIGATIVE":"ou'a",
"VOCATIVE":"ë"
}

var function_recog = {
"a":"st",
"e":"st",
"u":"st",
"o":"st",
"ö":"st",
"î":"st",
"â":"st",
"ê":"st",
"ô":"st",
"i":"dy",
"ai":"dy",
"ei":"dy",
"au":"dy",
"eu":"dy",
"iu":"dy",
"ia":"dy",
"ie":"dy",
"io":"dy",
"ui":"ma",
"ü":"ma",
"ëi":"ma",
"ae":"ma",
"ea":"ma",
"oa":"ma",
"üa":"ma",
"iù":"ma",
"iö":"ma",
"oi":"de",
"eo":"de",
"eö":"de",
"oe":"de",
"öe":"de",
"ëu":"de",
"üo":"de",
"üe":"de",
"üö":"de"
}

var modality = {
"(no modality)":"a",
"Desiderative (want to)":"u",
"Aspirative (hope to, wish that)":"e",
"Expectative (expect)":"o",
"Credential (believe, think that)":"i",
"Requisitive (request)":"ö",
"Exhortative (demand)":"î",
"Opportunitive (have the opportunity to, be able to)":"â",
"Capacitative (have the ability to, be able, can":"ê",
"Permissive (be permitted to)":"ô",
"Potential (have the potential to, have the possibility of)":"ü",
"Compulsory (must, be obliged to, have to)":"ai",
"Obligative (should, ought to, it would be best if":"ei",
"Impositive (be supposed to, expected to)":"ui",
"Advocative (suggest that, propose that)":"oi",
"Intentive (intend to, plan on, shall)":"iu",
"Anticipative (look forward to, eagerly await)":"au",
"Dispositive (be willing to)":"eu",
"Preparative (be ready to, prepared to)":"ou",
"Necessitative (need to, be necessary to)":"ae",
"Decisive (decide to, choose to)":"ia",
"Proclivitive (tend to, be apt to, prone to)":"ie",
"Voluntative (offer to, volunteer to)":"io",
"Accordative (agree to)":"iö",
"Inclinative (to feel like, be up for)":"ea",
"Compulsive (feel driven to, feel a need to)":"oa",
"Divertive (like to, enjoy)":"öi",
"Devotive (be devoted to, be committed to)":"öu",
"Preferential (prefer, would rather that)":"eo",
"Impressional (have an impression that, have a hunch that, feel that)":"ëi",
"Promissory (promise, swear that)":"ëu"
}

var numbers_100 = {
"1":"allal",
"2":"ksal",
"3":"ţkal",
"4":"apxal",
"5":"sţal",
"6":"acqal",
"7":"ansal",
"8":"fyal",
"9":"axmal",
"10":"mřal",
"11":"allalik",
"12":"ksalik",
"13":"ţkalik",
"14":"apxalik",
"15":"sţalik",
"16":"acqalik",
"17":"ansalik",
"18":"fyalik",
"19":"axmalik",
"20":"mřalik",
"21":"allalök",
"22":"ksalök",
"23":"ţkalök",
"24":"apxalök",
"25":"sţalök",
"26":"acqalök",
"27":"ansalök",
"28":"fyalök",
"29":"axmalök",
"30":"mřalök",
"31":"allalek",
"32":"ksalek",
"33":"ţkalek",
"34":"apxalek",
"35":"sţalek",
"36":"acqalek",
"37":"ansalek",
"38":"fyalek",
"39":"axmalek",
"40":"mřalek",
"41":"allalîk",
"42":"ksalîk",
"43":"ţkalîk",
"44":"apxalîk",
"45":"sţalîk",
"46":"acqalîk",
"47":"ansalîk",
"48":"fyalîk",
"49":"axmalîk",
"50":"mřalîk",
"51":"allalak",
"52":"ksalak",
"53":"ţkalak",
"54":"apxalak",
"55":"sţalak",
"56":"acqalak",
"57":"ansalak",
"58":"fyalak",
"59":"axmalak",
"60":"mřalak",
"61":"allalûk",
"62":"ksalûk",
"63":"ţkalûk",
"64":"apxalûk",
"65":"sţalûk",
"66":"acqalûk",
"67":"ansalûk",
"68":"fyalûk",
"69":"axmalûk",
"70":"mřalûk",
"71":"allalok",
"72":"ksalok",
"73":"ţkalok",
"74":"apxalok",
"75":"sţalok",
"76":"acqalok",
"77":"ansalok",
"78":"fyalok",
"79":"axmalok",
"80":"mřalok",
"81":"allalük",
"82":"ksalük",
"83":"ţkalük",
"84":"apxalük",
"85":"sţalük",
"86":"acqalük",
"87":"ansalük",
"88":"fyalük",
"89":"axmalük",
"90":"mřalük",
"91":"allaluk",
"92":"ksaluk",
"93":"ţkaluk",
"94":"apxaluk",
"95":"sţaluk",
"96":"acqaluk",
"97":"ansaluk",
"98":"fyaluk",
"99":"axmaluk",
"100":"ňal"
}

var numbers_10  = {
"1":"allal",
"2":"ksal",
"3":"ţkal",
"4":"apxal",
"5":"sţal",
"6":"acqal",
"7":"ansal",
"8":"fyal",
"9":"axmal",
"10":"mřal"
}

var numbers_recog_100 = {
"allal":"1",
"ksal":"2",
"ţkal":"3",
"apxal":"4",
"sţal":"5",
"acqal":"6",
"ansal":"7",
"fyal":"8",
"axmal":"9",
"mřal":"10",
"allalik":"11",
"ksalik":"12",
"ţkalik":"13",
"apxalik":"14",
"sţalik":"15",
"acqalik":"16",
"ansalik":"17",
"fyalik":"18",
"axmalik":"19",
"mřalik":"20",
"allalök":"21",
"ksalök":"22",
"ţkalök":"23",
"apxalök":"24",
"sţalök":"25",
"acqalök":"26",
"ansalök":"27",
"fyalök":"28",
"axmalök":"29",
"mřalök":"30",
"allalek":"31",
"ksalek":"32",
"ţkalek":"33",
"apxalek":"34",
"sţalek":"35",
"acqalek":"36",
"ansalek":"37",
"fyalek":"38",
"axmalek":"39",
"mřalek":"40",
"allalîk":"41",
"ksalîk":"42",
"ţkalîk":"43",
"apxalîk":"44",
"sţalîk":"45",
"acqalîk":"46",
"ansalîk":"47",
"fyalîk":"48",
"axmalîk":"49",
"mřalîk":"50",
"allalak":"51",
"ksalak":"52",
"ţkalak":"53",
"apxalak":"54",
"sţalak":"55",
"acqalak":"56",
"ansalak":"57",
"fyalak":"58",
"axmalak":"59",
"mřalak":"60",
"allalûk":"61",
"ksalûk":"62",
"ţkalûk":"63",
"apxalûk":"64",
"sţalûk":"65",
"acqalûk":"66",
"ansalûk":"67",
"fyalûk":"68",
"axmalûk":"69",
"mřalûk":"70",
"allalok":"71",
"ksalok":"72",
"ţkalok":"73",
"apxalok":"74",
"sţalok":"75",
"acqalok":"76",
"ansalok":"77",
"fyalok":"78",
"axmalok":"79",
"mřalok":"80",
"allalük":"81",
"ksalük":"82",
"ţkalük":"83",
"apxalük":"84",
"sţalük":"85",
"acqalük":"86",
"ansalük":"87",
"fyalük":"88",
"axmalük":"89",
"mřalük":"90",
"allaluk":"91",
"ksaluk":"92",
"ţkaluk":"93",
"apxaluk":"94",
"sţaluk":"95",
"acqaluk":"96",
"ansaluk":"97",
"fyaluk":"98",
"axmaluk":"99",
"ňal":"100"
}

var numbers_recog_10 = {
"allal":"1",
"ksal":"2",
"ţkal":"3",
"apxal":"4",
"sţal":"5",
"acqal":"6",
"ansal":"7",
"fyal":"8",
"axmal":"9",
"mřal":"10"
}

var vc_pos = {
"POSSESSIVE":"â",
"PROPRIETIVE":"î",
"GENITIVE":"ê",
"ATTRIBUTIVE":"ô",
"PRODUCTIVE":"ëi",
"INTERPRETATIVE":"öi",
"ORIGINATIVE":"ae"
}

var vc_spa = {
"LOCATIVE":"â'a",
"ORIENTATIVE":"ê'a",
"PROCURSIVE":"ô'a",
"ALLATIVE":"î'a",
"ABLATIVE":"ëu'a",
"NAVIGATIVE":"ou'a"
}

var stem_function_conjugation_1_3 = {
"Conjugate <b>a</b> into DYNAMIC":"i",
"Conjugate <b>e</b> into DYNAMIC":"ai",
"Conjugate <b>u</b> into DYNAMIC":"ei",
"Conjugate <b>a</b> into MANIFESTIVE":"ui",
"Conjugate <b>e</b> into MANIFESTIVE":"ü",
"Conjugate <b>u</b> into MANIFESTIVE":"ëi",
"Conjugate <b>a</b> into DESCRIPTIVE":"oi",
"Conjugate <b>e</b> into DESCRIPTIVE":"eo",
"Conjugate <b>u</b> into DESCRIPTIVE":"eö"
}

var stem_function_conjugation_4_6 = {
"Conjugate <b>o</b> into DYNAMIC":"au",
"Conjugate <b>ö</b> into DYNAMIC":"eu",
"Conjugate <b>î</b> into DYNAMIC":"iu",
"Conjugate <b>o</b> into MANIFESTIVE":"ae",
"Conjugate <b>ö</b> into MANIFESTIVE":"ea",
"Conjugate <b>î</b> into MANIFESTIVE":"oa",
"Conjugate <b>o</b> into DESCRIPTIVE":"oe",
"Conjugate <b>ö</b> into DESCRIPTIVE":"öe",
"Conjugate <b>î</b> into DESCRIPTIVE":"ëu"
}

var stem_function_conjugation_7_9 = {
"Conjugate <b>â</b> into DYNAMIC":"ia",
"Conjugate <b>ê</b> into DYNAMIC":"ie",
"Conjugate <b>ô</b> into DYNAMIC":"io",
"Conjugate <b>â</b> into MANIFESTIVE":"üa",
"Conjugate <b>ê</b> into MANIFESTIVE":"iù",
"Conjugate <b>ô</b> into MANIFESTIVE":"iö",
"Conjugate <b>â</b> into DESCRIPTIVE":"üo",
"Conjugate <b>ê</b> into DESCRIPTIVE":"üe",
"Conjugate <b>ô</b> into DESCRIPTIVE":"üo"

}

var stem_function_conjugation = {
"Conjugate <b>a</b> into DYNAMIC":"i",
"Conjugate <b>e</b> into DYNAMIC":"ai",
"Conjugate <b>u</b> into DYNAMIC":"ei",
"Conjugate <b>o</b> into DYNAMIC":"au",
"Conjugate <b>ö</b> into DYNAMIC":"eu",
"Conjugate <b>î</b> into DYNAMIC":"iu",
"Conjugate <b>â</b> into DYNAMIC":"ia",
"Conjugate <b>ê</b> into DYNAMIC":"ie",
"Conjugate <b>ô</b> into DYNAMIC":"io",
"Conjugate <b>a</b> into MANIFESTIVE":"ui",
"Conjugate <b>e</b> into MANIFESTIVE":"ü",
"Conjugate <b>u</b> into MANIFESTIVE":"ëi",
"Conjugate <b>o</b> into MANIFESTIVE":"ae",
"Conjugate <b>ö</b> into MANIFESTIVE":"ea",
"Conjugate <b>î</b> into MANIFESTIVE":"oa",
"Conjugate <b>â</b> into MANIFESTIVE":"üa",
"Conjugate <b>ê</b> into MANIFESTIVE":"iù",
"Conjugate <b>ô</b> into MANIFESTIVE":"iö",
"Conjugate <b>a</b> into DESCRIPTIVE":"oi",
"Conjugate <b>e</b> into DESCRIPTIVE":"eo",
"Conjugate <b>u</b> into DESCRIPTIVE":"eö",
"Conjugate <b>o</b> into DESCRIPTIVE":"oe",
"Conjugate <b>ö</b> into DESCRIPTIVE":"öe",
"Conjugate <b>î</b> into DESCRIPTIVE":"ëu",
"Conjugate <b>â</b> into DESCRIPTIVE":"üo",
"Conjugate <b>ê</b> into DESCRIPTIVE":"üe",
"Conjugate <b>ô</b> into DESCRIPTIVE":"üo"
}

var vc_tem = {
"SIMULTANEITIVE":"a'a",
"ASSESSIVE":"e'a",
"CONCURSIVE":"i'a",
"ACCESSIVE":"o'a",
"DIFFUSIVE":"u'a",
"PERIODIC":"ö'a",
"PROLAPSIVE":"ü'",
"PRECURSIVE":"ai'a",
"POSTCURSIVE":"ei'a",
"ELAPSIVE":"ui'a",
"ALLAPSIVE":"oi'a",
"INTERPOLATIVE":"ëi'a",
"EPISODIC":"au'a",
"PROLIMITIVE":"eu'a",
"LIMITATIVE":"iu'a"
}

var vc_trs = {
"OBLIQUE":"a",
"INDUCIVE":"u",
"ABSOLUTIVE":"e",
"ERGATIVE":"o",
"EFFECTUATIVE":"ö",
"AFFECTIVE":"i",
"DATIVE":"ü",
"INSTRUMENTAL":"ai",
"ACTIVATIVE":"ei",
"DERIVATIVE":"ui",
"SITUATIVE":"oi"
}
var ca = {
"NRM_DEL_M_CSL_UNI": "l", "NRM_DEL_M_ASO_UNI": "r", "NRM_DEL_M_VAR_UNI": "m", "NRM_DEL_M_COA_UNI": "n", "NRM_DEL_U_CSL_UNI": "t", "NRM_DEL_U_ASO_UNI": "k", "NRM_DEL_U_VAR_UNI": "p", "NRM_DEL_U_COA_UNI": "q", "NRM_DEL_N_CSL_UNI": "ţ", "NRM_DEL_N_ASO_UNI": "x", "NRM_DEL_N_VAR_UNI": "f", "NRM_DEL_N_COA_UNI": "xh", "NRM_DEL_A_CSL_UNI": "c", "NRM_DEL_A_ASO_UNI": "č", "NRM_DEL_A_VAR_UNI": "ż", "NRM_DEL_A_COA_UNI": "j", "NRM_DEL_M_CSL_DPX": "ll", "NRM_DEL_M_ASO_DPX": "rr", "NRM_DEL_M_VAR_DPX": "mm", "NRM_DEL_M_COA_DPX": "nn", "NRM_DEL_U_CSL_DPX": "ļt", "NRM_DEL_U_ASO_DPX": "ļk", "NRM_DEL_U_VAR_DPX": "ļp", "NRM_DEL_U_COA_DPX": "ļq", "NRM_DEL_N_CSL_DPX": "ţţ", "NRM_DEL_N_ASO_DPX": "xx", "NRM_DEL_N_VAR_DPX": "ff", "NRM_DEL_N_COA_DPX": "xxh", "NRM_DEL_A_CSL_DPX": "cc", "NRM_DEL_A_ASO_DPX": "čč", "NRM_DEL_A_VAR_DPX": "żż", "NRM_DEL_A_COA_DPX": "jj", "NRM_DEL_M_CSL_DCT": "tļ", "NRM_DEL_M_ASO_DCT": "lļ", "NRM_DEL_M_VAR_DCT": "lm", "NRM_DEL_M_COA_DCT": "ln", "NRM_DEL_U_CSL_DCT": "lt", "NRM_DEL_U_ASO_DCT": "lk", "NRM_DEL_U_VAR_DCT": "lp", "NRM_DEL_U_COA_DCT": "lq", "NRM_DEL_N_CSL_DCT": "lţ", "NRM_DEL_N_ASO_DCT": "lx", "NRM_DEL_N_VAR_DCT": "lf", "NRM_DEL_N_COA_DCT": "lxh", "NRM_DEL_A_CSL_DCT": "lc", "NRM_DEL_A_ASO_DCT": "lč", "NRM_DEL_A_VAR_DCT": "lż", "NRM_DEL_A_COA_DCT": "lj", "NRM_DEL_M_CSL_AGG": "ļ", "NRM_DEL_M_ASO_AGG": "rl", "NRM_DEL_M_VAR_AGG": "rm", "NRM_DEL_M_COA_AGG": "rn", "NRM_DEL_U_CSL_AGG": "rt", "NRM_DEL_U_ASO_AGG": "rk", "NRM_DEL_U_VAR_AGG": "rp", "NRM_DEL_U_COA_AGG": "rq", "NRM_DEL_N_CSL_AGG": "rţ", "NRM_DEL_N_ASO_AGG": "rx", "NRM_DEL_N_VAR_AGG": "rf", "NRM_DEL_N_COA_AGG": "rxh", "NRM_DEL_A_CSL_AGG": "rc", "NRM_DEL_A_ASO_AGG": "rč", "NRM_DEL_A_VAR_AGG": "rż", "NRM_DEL_A_COA_AGG": "rj", "NRM_DEL_M_CSL_SEG": "ļļ", "NRM_DEL_M_ASO_SEG": "rļ", "NRM_DEL_M_VAR_SEG": "mļ", "NRM_DEL_M_COA_SEG": "nļ", "NRM_DEL_U_CSL_SEG": "nt", "NRM_DEL_U_ASO_SEG": "ňk", "NRM_DEL_U_VAR_SEG": "mp", "NRM_DEL_U_COA_SEG": "ňq", "NRM_DEL_N_CSL_SEG": "nţ", "NRM_DEL_N_ASO_SEG": "ňx", "NRM_DEL_N_VAR_SEG": "mf", "NRM_DEL_N_COA_SEG": "ňxh", "NRM_DEL_A_CSL_SEG": "ns", "NRM_DEL_A_ASO_SEG": "nš", "NRM_DEL_A_VAR_SEG": "nz", "NRM_DEL_A_COA_SEG": "nž", "NRM_DEL_M_CSL_CPN": "řļ", "NRM_DEL_M_ASO_CPN": "řl", "NRM_DEL_M_VAR_CPN": "řm", "NRM_DEL_M_COA_CPN": "řn", "NRM_DEL_U_CSL_CPN": "řt", "NRM_DEL_U_ASO_CPN": "řk", "NRM_DEL_U_VAR_CPN": "řp", "NRM_DEL_U_COA_CPN": "řq", "NRM_DEL_N_CSL_CPN": "řţ", "NRM_DEL_N_ASO_CPN": "mx", "NRM_DEL_N_VAR_CPN": "řf", "NRM_DEL_N_COA_CPN": "mxh", "NRM_DEL_A_CSL_CPN": "řc", "NRM_DEL_A_ASO_CPN": "řč", "NRM_DEL_A_VAR_CPN": "řż", "NRM_DEL_A_COA_CPN": "řj", "NRM_DEL_M_CSL_COH": "sk", "NRM_DEL_M_ASO_COH": "st", "NRM_DEL_M_VAR_COH": "sp", "NRM_DEL_M_COA_COH": "sq", "NRM_DEL_U_CSL_COH": "ňt", "NRM_DEL_U_ASO_COH": "kt", "NRM_DEL_U_VAR_COH": "pt", "NRM_DEL_U_COA_COH": "qt", "NRM_DEL_N_CSL_COH": "sţ", "NRM_DEL_N_ASO_COH": "sx", "NRM_DEL_N_VAR_COH": "sf", "NRM_DEL_N_COA_COH": "sxh", "NRM_DEL_A_CSL_COH": "sc", "NRM_DEL_A_ASO_COH": "šč", "NRM_DEL_A_VAR_COH": "ţf", "NRM_DEL_A_COA_COH": "fţ", "NRM_DEL_M_CSL_CST": "šk", "NRM_DEL_M_ASO_CST": "št", "NRM_DEL_M_VAR_CST": "šp", "NRM_DEL_M_COA_CST": "šq", "NRM_DEL_U_CSL_CST": "ňd", "NRM_DEL_U_ASO_CST": "xt", "NRM_DEL_U_VAR_CST": "ft", "NRM_DEL_U_COA_CST": "xht", "NRM_DEL_N_CSL_CST": "šţ", "NRM_DEL_N_ASO_CST": "šx", "NRM_DEL_N_VAR_CST": "šf", "NRM_DEL_N_COA_CST": "šxh", "NRM_DEL_A_CSL_CST": "fk", "NRM_DEL_A_ASO_CST": "ţk", "NRM_DEL_A_VAR_CST": "ţs", "NRM_DEL_A_COA_CST": "ţš", "NRM_DEL_M_CSL_MLT": "kţ", "NRM_DEL_M_ASO_MLT": "kç", "NRM_DEL_M_VAR_MLT": "pţ", "NRM_DEL_M_COA_MLT": "qţ", "NRM_DEL_U_CSL_MLT": "çt", "NRM_DEL_U_ASO_MLT": "çk", "NRM_DEL_U_VAR_MLT": "çp", "NRM_DEL_U_COA_MLT": "çq", "NRM_DEL_N_CSL_MLT": "tf", "NRM_DEL_N_ASO_MLT": "kf", "NRM_DEL_N_VAR_MLT": "pf", "NRM_DEL_N_COA_MLT": "qf", "NRM_DEL_A_CSL_MLT": "fq", "NRM_DEL_A_ASO_MLT": "ţq", "NRM_DEL_A_VAR_MLT": "ţc", "NRM_DEL_A_COA_MLT": "ţč", "NRM_ICP_M_CSL_UNI": "mt", "NRM_ICP_M_ASO_UNI": "mk", "NRM_ICP_M_VAR_UNI": "ňp", "NRM_ICP_M_COA_UNI": "mq", "NRM_ICP_U_CSL_UNI": "pk", "NRM_ICP_U_ASO_UNI": "tk", "NRM_ICP_U_VAR_UNI": "tp", "NRM_ICP_U_COA_UNI": "kp", "NRM_ICP_N_CSL_UNI": "pq", "NRM_ICP_N_ASO_UNI": "tq", "NRM_ICP_N_VAR_UNI": "qp", "NRM_ICP_N_COA_UNI": "pļ", "NRM_ICP_A_CSL_UNI": "fst", "NRM_ICP_A_ASO_UNI": "fšt", "NRM_ICP_A_VAR_UNI": "fsk", "NRM_ICP_A_COA_UNI": "fšk", "NRM_ICP_M_CSL_DPX": "mt'", "NRM_ICP_M_ASO_DPX": "mk'", "NRM_ICP_M_VAR_DPX": "ňp'", "NRM_ICP_M_COA_DPX": "mq'", "NRM_ICP_U_CSL_DPX": "pk'", "NRM_ICP_U_ASO_DPX": "tk'", "NRM_ICP_U_VAR_DPX": "tp'", "NRM_ICP_U_COA_DPX": "kp'", "NRM_ICP_N_CSL_DPX": "pq'", "NRM_ICP_N_ASO_DPX": "tq'", "NRM_ICP_N_VAR_DPX": "qp'", "NRM_ICP_N_COA_DPX": "tç", "NRM_ICP_A_CSL_DPX": "fc'", "NRM_ICP_A_ASO_DPX": "fč'", "NRM_ICP_A_VAR_DPX": "fch", "NRM_ICP_A_COA_DPX": "fčh", "NRM_ICP_M_CSL_DCT": "skh", "NRM_ICP_M_ASO_DCT": "sth", "NRM_ICP_M_VAR_DCT": "sph", "NRM_ICP_M_COA_DCT": "sqh", "NRM_ICP_U_CSL_DCT": "škh", "NRM_ICP_U_ASO_DCT": "šth", "NRM_ICP_U_VAR_DCT": "šph", "NRM_ICP_U_COA_DCT": "šqh", "NRM_ICP_N_CSL_DCT": "fg", "NRM_ICP_N_ASO_DCT": "ţg", "NRM_ICP_N_VAR_DCT": "xhp", "NRM_ICP_N_COA_DCT": "xhp'", "NRM_ICP_A_CSL_DCT": "fc", "NRM_ICP_A_ASO_DCT": "fč", "NRM_ICP_A_VAR_DCT": "rfs", "NRM_ICP_A_COA_DCT": "rfš", "NRM_ICP_M_CSL_AGG": "sk'", "NRM_ICP_M_ASO_AGG": "st'", "NRM_ICP_M_VAR_AGG": "sp'", "NRM_ICP_M_COA_AGG": "sq'", "NRM_ICP_U_CSL_AGG": "šk'", "NRM_ICP_U_ASO_AGG": "št'", "NRM_ICP_U_VAR_AGG": "šp'", "NRM_ICP_U_COA_AGG": "šq'", "NRM_ICP_N_CSL_AGG": "bg", "NRM_ICP_N_ASO_AGG": "dg", "NRM_ICP_N_VAR_AGG": "xp", "NRM_ICP_N_COA_AGG": "ţp", "NRM_ICP_A_CSL_AGG": "lfs", "NRM_ICP_A_ASO_AGG": "lfš", "NRM_ICP_A_VAR_AGG": "fsq", "NRM_ICP_A_COA_AGG": "fšq", "NRM_ICP_M_CSL_SEG": "mth", "NRM_ICP_M_ASO_SEG": "mkh", "NRM_ICP_M_VAR_SEG": "ňph", "NRM_ICP_M_COA_SEG": "mqh", "NRM_ICP_U_CSL_SEG": "pkh", "NRM_ICP_U_ASO_SEG": "tkh", "NRM_ICP_U_VAR_SEG": "tph", "NRM_ICP_U_COA_SEG": "kph", "NRM_ICP_N_CSL_SEG": "pqh", "NRM_ICP_N_ASO_SEG": "tqh", "NRM_ICP_N_VAR_SEG": "sch", "NRM_ICP_N_COA_SEG": "ščh", "NRM_ICP_A_CSL_SEG": "xc'", "NRM_ICP_A_ASO_SEG": "xč'", "NRM_ICP_A_VAR_SEG": "xch", "NRM_ICP_A_COA_SEG": "xčh", "NRM_ICP_M_CSL_CPN": "pst'", "NRM_ICP_M_ASO_CPN": "kst'", "NRM_ICP_M_VAR_CPN": "psk'", "NRM_ICP_M_COA_CPN": "ksp'", "NRM_ICP_U_CSL_CPN": "fk'", "NRM_ICP_U_ASO_CPN": "ţk'", "NRM_ICP_U_VAR_CPN": "ţp'", "NRM_ICP_U_COA_CPN": "xp'", "NRM_ICP_N_CSL_CPN": "vg", "NRM_ICP_N_ASO_CPN": "dhg", "NRM_ICP_N_VAR_CPN": "sc'", "NRM_ICP_N_COA_CPN": "šč'", "NRM_ICP_A_CSL_CPN": "ţc'", "NRM_ICP_A_ASO_CPN": "ţč'", "NRM_ICP_A_VAR_CPN": "ţch", "NRM_ICP_A_COA_CPN": "ţčh", "NRM_ICP_M_CSL_COH": "psth", "NRM_ICP_M_ASO_COH": "ksth", "NRM_ICP_M_VAR_COH": "pskh", "NRM_ICP_M_COA_COH": "ksph", "NRM_ICP_U_CSL_COH": "fkh", "NRM_ICP_U_ASO_COH": "ţkh", "NRM_ICP_U_VAR_COH": "ţph", "NRM_ICP_U_COA_COH": "xph", "NRM_ICP_N_CSL_COH": "fp", "NRM_ICP_N_ASO_COH": "vd", "NRM_ICP_N_VAR_COH": "ňqf", "NRM_ICP_N_COA_COH": "vb", "NRM_ICP_A_CSL_COH": "ltf", "NRM_ICP_A_ASO_COH": "lkf", "NRM_ICP_A_VAR_COH": "xhph", "NRM_ICP_A_COA_COH": "qph", "NRM_ICP_M_CSL_CST": "pšt'", "NRM_ICP_M_ASO_CST": "kšt'", "NRM_ICP_M_VAR_CST": "pšk'", "NRM_ICP_M_COA_CST": "kšp'", "NRM_ICP_U_CSL_CST": "psq'", "NRM_ICP_U_ASO_CST": "ksk'", "NRM_ICP_U_VAR_CST": "pšq'", "NRM_ICP_U_COA_CST": "kšk'", "NRM_ICP_N_CSL_CST": "fq'", "NRM_ICP_N_ASO_CST": "ţq'", "NRM_ICP_N_VAR_CST": "gb", "NRM_ICP_N_COA_CST": "dhz", "NRM_ICP_A_CSL_CST": "fst'", "NRM_ICP_A_ASO_CST": "fšt'", "NRM_ICP_A_VAR_CST": "fsk'", "NRM_ICP_A_COA_CST": "fšk'", "NRM_ICP_M_CSL_MLT": "pšth", "NRM_ICP_M_ASO_MLT": "kšth", "NRM_ICP_M_VAR_MLT": "pškh", "NRM_ICP_M_COA_MLT": "kšph", "NRM_ICP_U_CSL_MLT": "psqh", "NRM_ICP_U_ASO_MLT": "kskh", "NRM_ICP_U_VAR_MLT": "pšqh", "NRM_ICP_U_COA_MLT": "kškh", "NRM_ICP_N_CSL_MLT": "fqh", "NRM_ICP_N_ASO_MLT": "ţqh", "NRM_ICP_N_VAR_MLT": "kkç", "NRM_ICP_N_COA_MLT": "pçç", "NRM_ICP_A_CSL_MLT": "fsth", "NRM_ICP_A_ASO_MLT": "fšth", "NRM_ICP_A_VAR_MLT": "fskh", "NRM_ICP_A_COA_MLT": "fškh", "NRM_PRX_M_CSL_UNI": "s", "NRM_PRX_M_ASO_UNI": "š", "NRM_PRX_M_VAR_UNI": "z", "NRM_PRX_M_COA_UNI": "ž", "NRM_PRX_U_CSL_UNI": "d", "NRM_PRX_U_ASO_UNI": "g", "NRM_PRX_U_VAR_UNI": "b", "NRM_PRX_U_COA_UNI": "ň", "NRM_PRX_N_CSL_UNI": "dh", "NRM_PRX_N_ASO_UNI": "ç", "NRM_PRX_N_VAR_UNI": "v", "NRM_PRX_N_COA_UNI": "ř", "NRM_PRX_A_CSL_UNI": "ck", "NRM_PRX_A_ASO_UNI": "ct", "NRM_PRX_A_VAR_UNI": "cp", "NRM_PRX_A_COA_UNI": "cq", "NRM_PRX_M_CSL_DPX": "ss", "NRM_PRX_M_ASO_DPX": "šš", "NRM_PRX_M_VAR_DPX": "zz", "NRM_PRX_M_COA_DPX": "žž", "NRM_PRX_U_CSL_DPX": "dv", "NRM_PRX_U_ASO_DPX": "gv", "NRM_PRX_U_VAR_DPX": "bv", "NRM_PRX_U_COA_DPX": "ňň", "NRM_PRX_N_CSL_DPX": "ddh", "NRM_PRX_N_ASO_DPX": "çç", "NRM_PRX_N_VAR_DPX": "vv", "NRM_PRX_N_COA_DPX": "řř", "NRM_PRX_A_CSL_DPX": "čk", "NRM_PRX_A_ASO_DPX": "čt", "NRM_PRX_A_VAR_DPX": "čp", "NRM_PRX_A_COA_DPX": "čq", "NRM_PRX_M_CSL_DCT": "ls", "NRM_PRX_M_ASO_DCT": "lš", "NRM_PRX_M_VAR_DCT": "lz", "NRM_PRX_M_COA_DCT": "lž", "NRM_PRX_U_CSL_DCT": "ld", "NRM_PRX_U_ASO_DCT": "lg", "NRM_PRX_U_VAR_DCT": "lb", "NRM_PRX_U_COA_DCT": "ňç", "NRM_PRX_N_CSL_DCT": "ldh", "NRM_PRX_N_ASO_DCT": "lç", "NRM_PRX_N_VAR_DCT": "lv", "NRM_PRX_N_COA_DCT": "rbv", "NRM_PRX_A_CSL_DCT": "ps", "NRM_PRX_A_ASO_DCT": "pš", "NRM_PRX_A_VAR_DCT": "bz", "NRM_PRX_A_COA_DCT": "bž", "NRM_PRX_M_CSL_AGG": "rs", "NRM_PRX_M_ASO_AGG": "rš", "NRM_PRX_M_VAR_AGG": "rz", "NRM_PRX_M_COA_AGG": "rž", "NRM_PRX_U_CSL_AGG": "rd", "NRM_PRX_U_ASO_AGG": "rg", "NRM_PRX_U_VAR_AGG": "rb", "NRM_PRX_U_COA_AGG": "rň", "NRM_PRX_N_CSL_AGG": "rdh", "NRM_PRX_N_ASO_AGG": "rç", "NRM_PRX_N_VAR_AGG": "rv", "NRM_PRX_N_COA_AGG": "rdv", "NRM_PRX_A_CSL_AGG": "ks", "NRM_PRX_A_ASO_AGG": "kš", "NRM_PRX_A_VAR_AGG": "gz", "NRM_PRX_A_COA_AGG": "gž", "NRM_PRX_M_CSL_SEG": "fs", "NRM_PRX_M_ASO_SEG": "fš", "NRM_PRX_M_VAR_SEG": "vz", "NRM_PRX_M_COA_SEG": "vž", "NRM_PRX_U_CSL_SEG": "nd", "NRM_PRX_U_ASO_SEG": "ňg", "NRM_PRX_U_VAR_SEG": "mb", "NRM_PRX_U_COA_SEG": "ňv", "NRM_PRX_N_CSL_SEG": "ndh", "NRM_PRX_N_ASO_SEG": "nç", "NRM_PRX_N_VAR_SEG": "mv", "NRM_PRX_N_COA_SEG": "rgv", "NRM_PRX_A_CSL_SEG": "gd", "NRM_PRX_A_ASO_SEG": "bd", "NRM_PRX_A_VAR_SEG": "pç", "NRM_PRX_A_COA_SEG": "řqf", "NRM_PRX_M_CSL_CPN": "řs", "NRM_PRX_M_ASO_CPN": "řš", "NRM_PRX_M_VAR_CPN": "řz", "NRM_PRX_M_COA_CPN": "řž", "NRM_PRX_U_CSL_CPN": "řd", "NRM_PRX_U_ASO_CPN": "řg", "NRM_PRX_U_VAR_CPN": "řb", "NRM_PRX_U_COA_CPN": "ř ň", "NRM_PRX_N_CSL_CPN": "řdh", "NRM_PRX_N_ASO_CPN": "řç", "NRM_PRX_N_VAR_CPN": "řv", "NRM_PRX_N_COA_CPN": "řxh", "NRM_PRX_A_CSL_CPN": "psk", "NRM_PRX_A_ASO_CPN": "pst", "NRM_PRX_A_VAR_CPN": "ksp", "NRM_PRX_A_COA_CPN": "kst", "NRM_PRX_M_CSL_COH": "ňs", "NRM_PRX_M_ASO_COH": "ňš", "NRM_PRX_M_VAR_COH": "ňz", "NRM_PRX_M_COA_COH": "ňž", "NRM_PRX_U_CSL_COH": "md", "NRM_PRX_U_ASO_COH": "ňkf", "NRM_PRX_U_VAR_COH": "ntf", "NRM_PRX_U_COA_COH": "ňf", "NRM_PRX_N_CSL_COH": "mdh", "NRM_PRX_N_ASO_COH": "mç", "NRM_PRX_N_VAR_COH": "ndv", "NRM_PRX_N_COA_COH": "mţ", "NRM_PRX_A_CSL_COH": "pšk", "NRM_PRX_A_ASO_COH": "pšt", "NRM_PRX_A_VAR_COH": "kšp", "NRM_PRX_A_COA_COH": "kšt", "NRM_PRX_M_CSL_CST": "ms", "NRM_PRX_M_ASO_CST": "mš", "NRM_PRX_M_VAR_CST": "mz", "NRM_PRX_M_COA_CST": "mž", "NRM_PRX_U_CSL_CST": "zd", "NRM_PRX_U_ASO_CST": "zg", "NRM_PRX_U_VAR_CST": "zb", "NRM_PRX_U_COA_CST": "řtf", "NRM_PRX_N_CSL_CST": "ţx", "NRM_PRX_N_ASO_CST": "fx", "NRM_PRX_N_VAR_CST": "xf", "NRM_PRX_N_COA_CST": "xhf", "NRM_PRX_A_CSL_CST": "ksk", "NRM_PRX_A_ASO_CST": "tx", "NRM_PRX_A_VAR_CST": "px", "NRM_PRX_A_COA_CST": "psq", "NRM_PRX_M_CSL_MLT": "mss", "NRM_PRX_M_ASO_MLT": "mšš", "NRM_PRX_M_VAR_MLT": "mzz", "NRM_PRX_M_COA_MLT": "mžž", "NRM_PRX_U_CSL_MLT": "žd", "NRM_PRX_U_ASO_MLT": "žg", "NRM_PRX_U_VAR_MLT": "žb", "NRM_PRX_U_COA_MLT": "řkf", "NRM_PRX_N_CSL_MLT": "ţxh", "NRM_PRX_N_ASO_MLT": "fxh", "NRM_PRX_N_VAR_MLT": "xţ", "NRM_PRX_N_COA_MLT": "xhţ", "NRM_PRX_A_CSL_MLT": "kšk", "NRM_PRX_A_ASO_MLT": "txh", "NRM_PRX_A_VAR_MLT": "pxh", "NRM_PRX_A_COA_MLT": "pšq", "NRM_TRM_M_CSL_UNI": "t'", "NRM_TRM_M_ASO_UNI": "k'", "NRM_TRM_M_VAR_UNI": "p'", "NRM_TRM_M_COA_UNI": "q'", "NRM_TRM_U_CSL_UNI": "th", "NRM_TRM_U_ASO_UNI": "kh", "NRM_TRM_U_VAR_UNI": "ph", "NRM_TRM_U_COA_UNI": "qh", "NRM_TRM_N_CSL_UNI": "c'", "NRM_TRM_N_ASO_UNI": "č'", "NRM_TRM_N_VAR_UNI": "ch", "NRM_TRM_N_COA_UNI": "čh", "NRM_TRM_A_CSL_UNI": "pss", "NRM_TRM_A_ASO_UNI": "pšš", "NRM_TRM_A_VAR_UNI": "kss", "NRM_TRM_A_COA_UNI": "kšš", "NRM_TRM_M_CSL_DPX": "ļt'", "NRM_TRM_M_ASO_DPX": "ļk'", "NRM_TRM_M_VAR_DPX": "ļp'", "NRM_TRM_M_COA_DPX": "ļq'", "NRM_TRM_U_CSL_DPX": "ļth", "NRM_TRM_U_ASO_DPX": "ļkh", "NRM_TRM_U_VAR_DPX": "ļph", "NRM_TRM_U_COA_DPX": "ļqh", "NRM_TRM_N_CSL_DPX": "cc'", "NRM_TRM_N_ASO_DPX": "čč'", "NRM_TRM_N_VAR_DPX": "cch", "NRM_TRM_N_COA_DPX": "ččh", "NRM_TRM_A_CSL_DPX": "rps", "NRM_TRM_A_ASO_DPX": "rpš", "NRM_TRM_A_VAR_DPX": "rks", "NRM_TRM_A_COA_DPX": "rkš", "NRM_TRM_M_CSL_DCT": "lt'", "NRM_TRM_M_ASO_DCT": "lk'", "NRM_TRM_M_VAR_DCT": "lp'", "NRM_TRM_M_COA_DCT": "lq'", "NRM_TRM_U_CSL_DCT": "lth", "NRM_TRM_U_ASO_DCT": "lkh", "NRM_TRM_U_VAR_DCT": "lph", "NRM_TRM_U_COA_DCT": "lqh", "NRM_TRM_N_CSL_DCT": "lc'", "NRM_TRM_N_ASO_DCT": "lč'", "NRM_TRM_N_VAR_DCT": "lch", "NRM_TRM_N_COA_DCT": "lčh", "NRM_TRM_A_CSL_DCT": "lps", "NRM_TRM_A_ASO_DCT": "lpš", "NRM_TRM_A_VAR_DCT": "lks", "NRM_TRM_A_COA_DCT": "lkš", "NRM_TRM_M_CSL_AGG": "rt'", "NRM_TRM_M_ASO_AGG": "rk'", "NRM_TRM_M_VAR_AGG": "rp'", "NRM_TRM_M_COA_AGG": "rq'", "NRM_TRM_U_CSL_AGG": "rth", "NRM_TRM_U_ASO_AGG": "rkh", "NRM_TRM_U_VAR_AGG": "rph", "NRM_TRM_U_COA_AGG": "rqh", "NRM_TRM_N_CSL_AGG": "rc'", "NRM_TRM_N_ASO_AGG": "rč'", "NRM_TRM_N_VAR_AGG": "rch", "NRM_TRM_N_COA_AGG": "rčh", "NRM_TRM_A_CSL_AGG": "rbz", "NRM_TRM_A_ASO_AGG": "rbž", "NRM_TRM_A_VAR_AGG": "rgz", "NRM_TRM_A_COA_AGG": "rgž", "NRM_TRM_M_CSL_SEG": "nt'", "NRM_TRM_M_ASO_SEG": "ňk'", "NRM_TRM_M_VAR_SEG": "mp'", "NRM_TRM_M_COA_SEG": "ňq'", "NRM_TRM_U_CSL_SEG": "nth", "NRM_TRM_U_ASO_SEG": "ňkh", "NRM_TRM_U_VAR_SEG": "mph", "NRM_TRM_U_COA_SEG": "ňqh", "NRM_TRM_N_CSL_SEG": "nc'", "NRM_TRM_N_ASO_SEG": "nč'", "NRM_TRM_N_VAR_SEG": "nch", "NRM_TRM_N_COA_SEG": "nčh", "NRM_TRM_A_CSL_SEG": "lbz", "NRM_TRM_A_ASO_SEG": "lbž", "NRM_TRM_A_VAR_SEG": "lgz", "NRM_TRM_A_COA_SEG": "lgž", "NRM_TRM_M_CSL_CPN": "řt'", "NRM_TRM_M_ASO_CPN": "řk'", "NRM_TRM_M_VAR_CPN": "řp'", "NRM_TRM_M_COA_CPN": "řq'", "NRM_TRM_U_CSL_CPN": "řth", "NRM_TRM_U_ASO_CPN": "řkh", "NRM_TRM_U_VAR_CPN": "řph", "NRM_TRM_U_COA_CPN": "řqh", "NRM_TRM_N_CSL_CPN": "řc'", "NRM_TRM_N_ASO_CPN": "řč'", "NRM_TRM_N_VAR_CPN": "řch", "NRM_TRM_N_COA_CPN": "čřh", "NRM_TRM_A_CSL_CPN": "řps", "NRM_TRM_A_ASO_CPN": "řpš", "NRM_TRM_A_VAR_CPN": "řks", "NRM_TRM_A_COA_CPN": "řkš", "NRM_TRM_M_CSL_COH": "ţsk'", "NRM_TRM_M_ASO_COH": "ţšk'", "NRM_TRM_M_VAR_COH": "fsq'", "NRM_TRM_M_COA_COH": "fšq'", "NRM_TRM_U_CSL_COH": "ţskh", "NRM_TRM_U_ASO_COH": "ţškh", "NRM_TRM_U_VAR_COH": "fsqh", "NRM_TRM_U_COA_COH": "fšqh", "NRM_TRM_N_CSL_COH": "mc'", "NRM_TRM_N_ASO_COH": "mč'", "NRM_TRM_N_VAR_COH": "mch", "NRM_TRM_N_COA_COH": "mčh", "NRM_TRM_A_CSL_COH": "řbz", "NRM_TRM_A_ASO_COH": "řbž", "NRM_TRM_A_VAR_COH": "řgz", "NRM_TRM_A_COA_COH": "řgž", "NRM_TRM_M_CSL_CST": "kt'", "NRM_TRM_M_ASO_CST": "ft'", "NRM_TRM_M_VAR_CST": "pt'", "NRM_TRM_M_COA_CST": "xht'", "NRM_TRM_U_CSL_CST": "kth", "NRM_TRM_U_ASO_CST": "fth", "NRM_TRM_U_VAR_CST": "pth", "NRM_TRM_U_COA_CST": "xhth", "NRM_TRM_N_CSL_CST": "ňc'", "NRM_TRM_N_ASO_CST": "ňč'", "NRM_TRM_N_VAR_CST": "ňch", "NRM_TRM_N_COA_CST": "ňčh", "NRM_TRM_A_CSL_CST": "ňss", "NRM_TRM_A_ASO_CST": "ňšš", "NRM_TRM_A_VAR_CST": "ňzz", "NRM_TRM_A_COA_CST": "ňžž", "NRM_TRM_M_CSL_MLT": "ňt'", "NRM_TRM_M_ASO_MLT": "xt'", "NRM_TRM_M_VAR_MLT": "fp'", "NRM_TRM_M_COA_MLT": "qt'", "NRM_TRM_U_CSL_MLT": "ňth", "NRM_TRM_U_ASO_MLT": "xth", "NRM_TRM_U_VAR_MLT": "fph", "NRM_TRM_U_COA_MLT": "qth", "NRM_TRM_N_CSL_MLT": "çt'", "NRM_TRM_N_ASO_MLT": "çk'", "NRM_TRM_N_VAR_MLT": "çp'", "NRM_TRM_N_COA_MLT": "çq'", "NRM_TRM_A_CSL_MLT": "çth", "NRM_TRM_A_ASO_MLT": "çkh", "NRM_TRM_A_VAR_MLT": "çph", "NRM_TRM_A_COA_MLT": "çqh", "NRM_DPL_M_CSL_UNI": "kc", "NRM_DPL_M_ASO_UNI": "żd", "NRM_DPL_M_VAR_UNI": "pc", "NRM_DPL_M_COA_UNI": "qc", "NRM_DPL_U_CSL_UNI": "kč", "NRM_DPL_U_ASO_UNI": "jd", "NRM_DPL_U_VAR_UNI": "pč", "NRM_DPL_U_COA_UNI": "qč", "NRM_DPL_N_CSL_UNI": "bdh", "NRM_DPL_N_ASO_UNI": "gdh", "NRM_DPL_N_VAR_UNI": "ţt", "NRM_DPL_N_COA_UNI": "db", "NRM_DPL_A_CSL_UNI": "bż", "NRM_DPL_A_ASO_UNI": "gż", "NRM_DPL_A_VAR_UNI": "bj", "NRM_DPL_A_COA_UNI": "gj", "NRM_DPL_M_CSL_DPX": "lkç", "NRM_DPL_M_ASO_DPX": "lţs", "NRM_DPL_M_VAR_DPX": "bzz", "NRM_DPL_M_COA_DPX": "gzz", "NRM_DPL_U_CSL_DPX": "rçç", "NRM_DPL_U_ASO_DPX": "lţš", "NRM_DPL_U_VAR_DPX": "bžž", "NRM_DPL_U_COA_DPX": "gžž", "NRM_DPL_N_CSL_DPX": "xpf", "NRM_DPL_N_ASO_DPX": "ňdh", "NRM_DPL_N_VAR_DPX": "dhd", "NRM_DPL_N_COA_DPX": "tçç", "NRM_DPL_A_CSL_DPX": "rpss", "NRM_DPL_A_ASO_DPX": "rkss", "NRM_DPL_A_VAR_DPX": "rpšš", "NRM_DPL_A_COA_DPX": "rkšš", "NRM_DPL_M_CSL_DCT": "lsk", "NRM_DPL_M_ASO_DCT": "lst", "NRM_DPL_M_VAR_DCT": "lsp", "NRM_DPL_M_COA_DCT": "lsq", "NRM_DPL_U_CSL_DCT": "lšk", "NRM_DPL_U_ASO_DCT": "lšt", "NRM_DPL_U_VAR_DCT": "lšp", "NRM_DPL_U_COA_DCT": "lšq", "NRM_DPL_N_CSL_DCT": "lvz", "NRM_DPL_N_ASO_DCT": "lvž", "NRM_DPL_N_VAR_DCT": "ldhz", "NRM_DPL_N_COA_DCT": "ldhž", "NRM_DPL_A_CSL_DCT": "lzb", "NRM_DPL_A_ASO_DCT": "lžb", "NRM_DPL_A_VAR_DCT": "lzg", "NRM_DPL_A_COA_DCT": "lžg", "NRM_DPL_M_CSL_AGG": "rsk", "NRM_DPL_M_ASO_AGG": "rst", "NRM_DPL_M_VAR_AGG": "rsp", "NRM_DPL_M_COA_AGG": "rsq", "NRM_DPL_U_CSL_AGG": "ršk", "NRM_DPL_U_ASO_AGG": "ršt", "NRM_DPL_U_VAR_AGG": "ršp", "NRM_DPL_U_COA_AGG": "ršq", "NRM_DPL_N_CSL_AGG": "rvz", "NRM_DPL_N_ASO_AGG": "rvž", "NRM_DPL_N_VAR_AGG": "rţs", "NRM_DPL_N_COA_AGG": "rţš", "NRM_DPL_A_CSL_AGG": "rzb", "NRM_DPL_A_ASO_AGG": "ržb", "NRM_DPL_A_VAR_AGG": "rzg", "NRM_DPL_A_COA_AGG": "ržg", "NRM_DPL_M_CSL_SEG": "nsk", "NRM_DPL_M_ASO_SEG": "nst", "NRM_DPL_M_VAR_SEG": "nsp", "NRM_DPL_M_COA_SEG": "nsq", "NRM_DPL_U_CSL_SEG": "nšk", "NRM_DPL_U_ASO_SEG": "nšt", "NRM_DPL_U_VAR_SEG": "nšp", "NRM_DPL_U_COA_SEG": "nšq", "NRM_DPL_N_CSL_SEG": "rbdh", "NRM_DPL_N_ASO_SEG": "rgdh", "NRM_DPL_N_VAR_SEG": "rqţ", "NRM_DPL_N_COA_SEG": "rkç", "NRM_DPL_A_CSL_SEG": "nzb", "NRM_DPL_A_ASO_SEG": "nžb", "NRM_DPL_A_VAR_SEG": "nzg", "NRM_DPL_A_COA_SEG": "nžg", "NRM_DPL_M_CSL_CPN": "řsk", "NRM_DPL_M_ASO_CPN": "řst", "NRM_DPL_M_VAR_CPN": "řsp", "NRM_DPL_M_COA_CPN": "řsq", "NRM_DPL_U_CSL_CPN": "řšk", "NRM_DPL_U_ASO_CPN": "řšt", "NRM_DPL_U_VAR_CPN": "řšp", "NRM_DPL_U_COA_CPN": "řšq", "NRM_DPL_N_CSL_CPN": "řpţ", "NRM_DPL_N_ASO_CPN": "řkţ", "NRM_DPL_N_VAR_CPN": "řqţ", "NRM_DPL_N_COA_CPN": "řkç", "NRM_DPL_A_CSL_CPN": "řzb", "NRM_DPL_A_ASO_CPN": "řžb", "NRM_DPL_A_VAR_CPN": "řzg", "NRM_DPL_A_COA_CPN": "řžg", "NRM_DPL_M_CSL_COH": "msk", "NRM_DPL_M_ASO_COH": "mst", "NRM_DPL_M_VAR_COH": "msp", "NRM_DPL_M_COA_COH": "msq", "NRM_DPL_U_CSL_COH": "mšk", "NRM_DPL_U_ASO_COH": "mšt", "NRM_DPL_U_VAR_COH": "mšp", "NRM_DPL_U_COA_COH": "mšq", "NRM_DPL_N_CSL_COH": "lpf", "NRM_DPL_N_ASO_COH": "lpç", "NRM_DPL_N_VAR_COH": "ňkç", "NRM_DPL_N_COA_COH": "mpç", "NRM_DPL_A_CSL_COH": "mzb", "NRM_DPL_A_ASO_COH": "mžb", "NRM_DPL_A_VAR_COH": "mzg", "NRM_DPL_A_COA_COH": "mžg", "NRM_DPL_M_CSL_CST": "ňsk", "NRM_DPL_M_ASO_CST": "ňst", "NRM_DPL_M_VAR_CST": "ňsp", "NRM_DPL_M_COA_CST": "ňsq", "NRM_DPL_U_CSL_CST": "ňšk", "NRM_DPL_U_ASO_CST": "ňšt", "NRM_DPL_U_VAR_CST": "ňšp", "NRM_DPL_U_COA_CST": "ňšq", "NRM_DPL_N_CSL_CST": "rpf", "NRM_DPL_N_ASO_CST": "rpç", "NRM_DPL_N_VAR_CST": "řpf", "NRM_DPL_N_COA_CST": "řpç", "NRM_DPL_A_CSL_CST": "řpss", "NRM_DPL_A_ASO_CST": "řkss", "NRM_DPL_A_VAR_CST": "řpšš", "NRM_DPL_A_COA_CST": "řkšš", "NRM_DPL_M_CSL_MLT": "ssk", "NRM_DPL_M_ASO_MLT": "sst", "NRM_DPL_M_VAR_MLT": "ssp", "NRM_DPL_M_COA_MLT": "ssq", "NRM_DPL_U_CSL_MLT": "ššk", "NRM_DPL_U_ASO_MLT": "ššt", "NRM_DPL_U_VAR_MLT": "ššp", "NRM_DPL_U_COA_MLT": "ššq", "NRM_DPL_N_CSL_MLT": "bzd", "NRM_DPL_N_ASO_MLT": "bžd", "NRM_DPL_N_VAR_MLT": "gzd", "NRM_DPL_N_COA_MLT": "gžd", "NRM_DPL_A_CSL_MLT": "gzb", "NRM_DPL_A_ASO_MLT": "gžb", "NRM_DPL_A_VAR_MLT": "bzg", "NRM_DPL_A_COA_MLT": "bžg", "NRM_GRA_M_CSL_UNI": "kc'", "NRM_GRA_M_ASO_UNI": "żb", "NRM_GRA_M_VAR_UNI": "pc'", "NRM_GRA_M_COA_UNI": "qc'", "NRM_GRA_U_CSL_UNI": "kč'", "NRM_GRA_U_ASO_UNI": "jb", "NRM_GRA_U_VAR_UNI": "pč'", "NRM_GRA_U_COA_UNI": "qč'", "NRM_GRA_N_CSL_UNI": "kch", "NRM_GRA_N_ASO_UNI": "żg", "NRM_GRA_N_VAR_UNI": "pch", "NRM_GRA_N_COA_UNI": "qch", "NRM_GRA_A_CSL_UNI": "kčh", "NRM_GRA_A_ASO_UNI": "jg", "NRM_GRA_A_VAR_UNI": "pčh", "NRM_GRA_A_COA_UNI": "qčh", "NRM_GRA_M_CSL_DPX": "ck'", "NRM_GRA_M_ASO_DPX": "ct'", "NRM_GRA_M_VAR_DPX": "cp'", "NRM_GRA_M_COA_DPX": "cq'", "NRM_GRA_U_CSL_DPX": "čk'", "NRM_GRA_U_ASO_DPX": "čt'", "NRM_GRA_U_VAR_DPX": "čp'", "NRM_GRA_U_COA_DPX": "čq'", "NRM_GRA_N_CSL_DPX": "ckh", "NRM_GRA_N_ASO_DPX": "cth", "NRM_GRA_N_VAR_DPX": "cph", "NRM_GRA_N_COA_DPX": "cqh", "NRM_GRA_A_CSL_DPX": "čkh", "NRM_GRA_A_ASO_DPX": "čth", "NRM_GRA_A_VAR_DPX": "čph", "NRM_GRA_A_COA_DPX": "čqh", "NRM_GRA_M_CSL_DCT": "lsk'", "NRM_GRA_M_ASO_DCT": "lst'", "NRM_GRA_M_VAR_DCT": "lsp'", "NRM_GRA_M_COA_DCT": "lsq'", "NRM_GRA_U_CSL_DCT": "lšk'", "NRM_GRA_U_ASO_DCT": "lšt'", "NRM_GRA_U_VAR_DCT": "lšp'", "NRM_GRA_U_COA_DCT": "lšq'", "NRM_GRA_N_CSL_DCT": "lskh", "NRM_GRA_N_ASO_DCT": "lsth", "NRM_GRA_N_VAR_DCT": "lsph", "NRM_GRA_N_COA_DCT": "lsqh", "NRM_GRA_A_CSL_DCT": "lškh", "NRM_GRA_A_ASO_DCT": "lšth", "NRM_GRA_A_VAR_DCT": "lšph", "NRM_GRA_A_COA_DCT": "lšqh", "NRM_GRA_M_CSL_AGG": "rsk'", "NRM_GRA_M_ASO_AGG": "rst'", "NRM_GRA_M_VAR_AGG": "rsp'", "NRM_GRA_M_COA_AGG": "rsq'", "NRM_GRA_U_CSL_AGG": "ršk'", "NRM_GRA_U_ASO_AGG": "ršt'", "NRM_GRA_U_VAR_AGG": "ršp'", "NRM_GRA_U_COA_AGG": "ršq'", "NRM_GRA_N_CSL_AGG": "rskh", "NRM_GRA_N_ASO_AGG": "rsth", "NRM_GRA_N_VAR_AGG": "rsph", "NRM_GRA_N_COA_AGG": "rsqh", "NRM_GRA_A_CSL_AGG": "rškh", "NRM_GRA_A_ASO_AGG": "ršth", "NRM_GRA_A_VAR_AGG": "ršph", "NRM_GRA_A_COA_AGG": "ršqh", "NRM_GRA_M_CSL_SEG": "nsk'", "NRM_GRA_M_ASO_SEG": "nst'", "NRM_GRA_M_VAR_SEG": "nsp'", "NRM_GRA_M_COA_SEG": "nsq'", "NRM_GRA_U_CSL_SEG": "nšk'", "NRM_GRA_U_ASO_SEG": "nšt'", "NRM_GRA_U_VAR_SEG": "nšp'", "NRM_GRA_U_COA_SEG": "nšq'", "NRM_GRA_N_CSL_SEG": "nskh", "NRM_GRA_N_ASO_SEG": "nsth", "NRM_GRA_N_VAR_SEG": "nsph", "NRM_GRA_N_COA_SEG": "nsqh", "NRM_GRA_A_CSL_SEG": "nškh", "NRM_GRA_A_ASO_SEG": "nšth", "NRM_GRA_A_VAR_SEG": "nšph", "NRM_GRA_A_COA_SEG": "nšqh", "NRM_GRA_M_CSL_CPN": "řsk'", "NRM_GRA_M_ASO_CPN": "řst'", "NRM_GRA_M_VAR_CPN": "řsp'", "NRM_GRA_M_COA_CPN": "řsq'", "NRM_GRA_U_CSL_CPN": "řšk'", "NRM_GRA_U_ASO_CPN": "řšt'", "NRM_GRA_U_VAR_CPN": "řšp'", "NRM_GRA_U_COA_CPN": "řšq'", "NRM_GRA_N_CSL_CPN": "řskh", "NRM_GRA_N_ASO_CPN": "řsth", "NRM_GRA_N_VAR_CPN": "řsph", "NRM_GRA_N_COA_CPN": "řsqh", "NRM_GRA_A_CSL_CPN": "řškh", "NRM_GRA_A_ASO_CPN": "řšth", "NRM_GRA_A_VAR_CPN": "řšph", "NRM_GRA_A_COA_CPN": "řšqh", "NRM_GRA_M_CSL_COH": "msk'", "NRM_GRA_M_ASO_COH": "mst'", "NRM_GRA_M_VAR_COH": "msp'", "NRM_GRA_M_COA_COH": "msq'", "NRM_GRA_U_CSL_COH": "mšk'", "NRM_GRA_U_ASO_COH": "mšt'", "NRM_GRA_U_VAR_COH": "mšp'", "NRM_GRA_U_COA_COH": "mšq'", "NRM_GRA_N_CSL_COH": "mskh", "NRM_GRA_N_ASO_COH": "msth", "NRM_GRA_N_VAR_COH": "msph", "NRM_GRA_N_COA_COH": "msqh", "NRM_GRA_A_CSL_COH": "mškh", "NRM_GRA_A_ASO_COH": "mšth", "NRM_GRA_A_VAR_COH": "mšph", "NRM_GRA_A_COA_COH": "mšqh", "NRM_GRA_M_CSL_CST": "ňsk'", "NRM_GRA_M_ASO_CST": "ňst'", "NRM_GRA_M_VAR_CST": "ňsp'", "NRM_GRA_M_COA_CST": "ňsq'", "NRM_GRA_U_CSL_CST": "ňšk'", "NRM_GRA_U_ASO_CST": "ňšt'", "NRM_GRA_U_VAR_CST": "ňšp'", "NRM_GRA_U_COA_CST": "ňšq'", "NRM_GRA_N_CSL_CST": "ňskh", "NRM_GRA_N_ASO_CST": "ňsth", "NRM_GRA_N_VAR_CST": "ňsph", "NRM_GRA_N_COA_CST": "ňsqh", "NRM_GRA_A_CSL_CST": "ňškh", "NRM_GRA_A_ASO_CST": "ňšth", "NRM_GRA_A_VAR_CST": "ňšph", "NRM_GRA_A_COA_CST": "ňšqh", "NRM_GRA_M_CSL_MLT": "ssk'", "NRM_GRA_M_ASO_MLT": "sst'", "NRM_GRA_M_VAR_MLT": "ssp'", "NRM_GRA_M_COA_MLT": "ssq'", "NRM_GRA_U_CSL_MLT": "ššk'", "NRM_GRA_U_ASO_MLT": "ššt'", "NRM_GRA_U_VAR_MLT": "ššp'", "NRM_GRA_U_COA_MLT": "ššq'", "NRM_GRA_N_CSL_MLT": "sskh", "NRM_GRA_N_ASO_MLT": "ssth", "NRM_GRA_N_VAR_MLT": "ssph", "NRM_GRA_N_COA_MLT": "ssqh", "NRM_GRA_A_CSL_MLT": "šškh", "NRM_GRA_A_ASO_MLT": "ššth", "NRM_GRA_A_VAR_MLT": "ššph", "NRM_GRA_A_COA_MLT": "ššqh", "RPV_DEL_M_CSL_UNI": "tt", "RPV_DEL_M_ASO_UNI": "kk", "RPV_DEL_M_VAR_UNI": "pp", "RPV_DEL_M_COA_UNI": "qq", "RPV_DEL_U_CSL_UNI": "dd", "RPV_DEL_U_ASO_UNI": "gg", "RPV_DEL_U_VAR_UNI": "bb", "RPV_DEL_U_COA_UNI": "cf", "RPV_DEL_N_CSL_UNI": "ţw", "RPV_DEL_N_ASO_UNI": "xw", "RPV_DEL_N_VAR_UNI": "fw", "RPV_DEL_N_COA_UNI": "xhw", "RPV_DEL_A_CSL_UNI": "sw", "RPV_DEL_A_ASO_UNI": "šw", "RPV_DEL_A_VAR_UNI": "zw", "RPV_DEL_A_COA_UNI": "žw", "RPV_DEL_M_CSL_DPX": "tt'", "RPV_DEL_M_ASO_DPX": "kk'", "RPV_DEL_M_VAR_DPX": "pp'", "RPV_DEL_M_COA_DPX": "qq'", "RPV_DEL_U_CSL_DPX": "nçw", "RPV_DEL_U_ASO_DPX": "ňçw", "RPV_DEL_U_VAR_DPX": "mçw", "RPV_DEL_U_COA_DPX": "čf", "RPV_DEL_N_CSL_DPX": "dhw", "RPV_DEL_N_ASO_DPX": "ňw", "RPV_DEL_N_VAR_DPX": "vw", "RPV_DEL_N_COA_DPX": "çw", "RPV_DEL_A_CSL_DPX": "cw", "RPV_DEL_A_ASO_DPX": "čw", "RPV_DEL_A_VAR_DPX": "żw", "RPV_DEL_A_COA_DPX": "jw", "RPV_DEL_M_CSL_DCT": "tth", "RPV_DEL_M_ASO_DCT": "kkh", "RPV_DEL_M_VAR_DCT": "pph", "RPV_DEL_M_COA_DCT": "qqh", "RPV_DEL_U_CSL_DCT": "pçw", "RPV_DEL_U_ASO_DCT": "kfw", "RPV_DEL_U_VAR_DCT": "pfw", "RPV_DEL_U_COA_DCT": "qfw", "RPV_DEL_N_CSL_DCT": "lţw", "RPV_DEL_N_ASO_DCT": "lxw", "RPV_DEL_N_VAR_DCT": "lfw", "RPV_DEL_N_COA_DCT": "lxhw", "RPV_DEL_A_CSL_DCT": "lsw", "RPV_DEL_A_ASO_DCT": "lšw", "RPV_DEL_A_VAR_DCT": "lzw", "RPV_DEL_A_COA_DCT": "lžw", "RPV_DEL_M_CSL_AGG": "lpt'", "RPV_DEL_M_ASO_AGG": "lkt'", "RPV_DEL_M_VAR_AGG": "lpk'", "RPV_DEL_M_COA_AGG": "ltk'", "RPV_DEL_U_CSL_AGG": "lft'", "RPV_DEL_U_ASO_AGG": "lxt'", "RPV_DEL_U_VAR_AGG": "lfk'", "RPV_DEL_U_COA_AGG": "lţk'", "RPV_DEL_N_CSL_AGG": "rţw", "RPV_DEL_N_ASO_AGG": "rxw", "RPV_DEL_N_VAR_AGG": "rfw", "RPV_DEL_N_COA_AGG": "rxhw", "RPV_DEL_A_CSL_AGG": "rsw", "RPV_DEL_A_ASO_AGG": "ršw", "RPV_DEL_A_VAR_AGG": "rzw", "RPV_DEL_A_COA_AGG": "ržw", "RPV_DEL_M_CSL_SEG": "rpt'", "RPV_DEL_M_ASO_SEG": "rkt'", "RPV_DEL_M_VAR_SEG": "rpk'", "RPV_DEL_M_COA_SEG": "rtk'", "RPV_DEL_U_CSL_SEG": "rft'", "RPV_DEL_U_ASO_SEG": "rxt'", "RPV_DEL_U_VAR_SEG": "rfk'", "RPV_DEL_U_COA_SEG": "rţk'", "RPV_DEL_N_CSL_SEG": "mţw", "RPV_DEL_N_ASO_SEG": "mxw", "RPV_DEL_N_VAR_SEG": "ňfw", "RPV_DEL_N_COA_SEG": "mxhw", "RPV_DEL_A_CSL_SEG": "msw", "RPV_DEL_A_ASO_SEG": "mšw", "RPV_DEL_A_VAR_SEG": "mzw", "RPV_DEL_A_COA_SEG": "mžw", "RPV_DEL_M_CSL_CPN": "řpt'", "RPV_DEL_M_ASO_CPN": "řkt'", "RPV_DEL_M_VAR_CPN": "řpk'", "RPV_DEL_M_COA_CPN": "řtk'", "RPV_DEL_U_CSL_CPN": "řft'", "RPV_DEL_U_ASO_CPN": "řxt'", "RPV_DEL_U_VAR_CPN": "řfk'", "RPV_DEL_U_COA_CPN": "řţk'", "RPV_DEL_N_CSL_CPN": "řţw", "RPV_DEL_N_ASO_CPN": "řxw", "RPV_DEL_N_VAR_CPN": "řfw", "RPV_DEL_N_COA_CPN": "tçw", "RPV_DEL_A_CSL_CPN": "řsw", "RPV_DEL_A_ASO_CPN": "řšw", "RPV_DEL_A_VAR_CPN": "řzw", "RPV_DEL_A_COA_CPN": "řžw", "RPV_DEL_M_CSL_COH": "lpth", "RPV_DEL_M_ASO_COH": "lkth", "RPV_DEL_M_VAR_COH": "lpkh", "RPV_DEL_M_COA_COH": "ltkh", "RPV_DEL_U_CSL_COH": "lfth", "RPV_DEL_U_ASO_COH": "lxth", "RPV_DEL_U_VAR_COH": "lfkh", "RPV_DEL_U_COA_COH": "lţkh", "RPV_DEL_N_CSL_COH": "nţw", "RPV_DEL_N_ASO_COH": "ňxw", "RPV_DEL_N_VAR_COH": "mfw", "RPV_DEL_N_COA_COH": "ňxhw", "RPV_DEL_A_CSL_COH": "nsw", "RPV_DEL_A_ASO_COH": "nšw", "RPV_DEL_A_VAR_COH": "nzw", "RPV_DEL_A_COA_COH": "nžw", "RPV_DEL_M_CSL_CST": "rpth", "RPV_DEL_M_ASO_CST": "rkth", "RPV_DEL_M_VAR_CST": "rpkh", "RPV_DEL_M_COA_CST": "rtkh", "RPV_DEL_U_CSL_CST": "rfth", "RPV_DEL_U_ASO_CST": "rxth", "RPV_DEL_U_VAR_CST": "rfkh", "RPV_DEL_U_COA_CST": "rţkh", "RPV_DEL_N_CSL_CST": "ldhw", "RPV_DEL_N_ASO_CST": "lňw", "RPV_DEL_N_VAR_CST": "lvw", "RPV_DEL_N_COA_CST": "lçw", "RPV_DEL_A_CSL_CST": "ňsw", "RPV_DEL_A_ASO_CST": "ňšw", "RPV_DEL_A_VAR_CST": "ňzw", "RPV_DEL_A_COA_CST": "ňžw", "RPV_DEL_M_CSL_MLT": "řpth", "RPV_DEL_M_ASO_MLT": "řkth", "RPV_DEL_M_VAR_MLT": "řpkh", "RPV_DEL_M_COA_MLT": "řtkh", "RPV_DEL_U_CSL_MLT": "řfth", "RPV_DEL_U_ASO_MLT": "řxth", "RPV_DEL_U_VAR_MLT": "řfkh", "RPV_DEL_U_COA_MLT": "řţkh", "RPV_DEL_N_CSL_MLT": "rdhw", "RPV_DEL_N_ASO_MLT": "rňw", "RPV_DEL_N_VAR_MLT": "rvw", "RPV_DEL_N_COA_MLT": "rçw", "RPV_DEL_A_CSL_MLT": "ssw", "RPV_DEL_A_ASO_MLT": "ššw", "RPV_DEL_A_VAR_MLT": "zzw", "RPV_DEL_A_COA_MLT": "žžw", "RPV_PRX_M_CSL_UNI": "tw", "RPV_PRX_M_ASO_UNI": "kw", "RPV_PRX_M_VAR_UNI": "pw", "RPV_PRX_M_COA_UNI": "qw", "RPV_PRX_U_CSL_UNI": "ty", "RPV_PRX_U_ASO_UNI": "ky", "RPV_PRX_U_VAR_UNI": "py", "RPV_PRX_U_COA_UNI": "my", "RPV_PRX_N_CSL_UNI": "dw", "RPV_PRX_N_ASO_UNI": "gw", "RPV_PRX_N_VAR_UNI": "bw", "RPV_PRX_N_COA_UNI": "lw", "RPV_PRX_A_CSL_UNI": "dy", "RPV_PRX_A_ASO_UNI": "gy", "RPV_PRX_A_VAR_UNI": "by", "RPV_PRX_A_COA_UNI": "ny", "RPV_PRX_M_CSL_DPX": "ttw", "RPV_PRX_M_ASO_DPX": "kkw", "RPV_PRX_M_VAR_DPX": "ppw", "RPV_PRX_M_COA_DPX": "qqw", "RPV_PRX_U_CSL_DPX": "tty", "RPV_PRX_U_ASO_DPX": "kky", "RPV_PRX_U_VAR_DPX": "ppy", "RPV_PRX_U_COA_DPX": "fty", "RPV_PRX_N_CSL_DPX": "ddw", "RPV_PRX_N_ASO_DPX": "ggw", "RPV_PRX_N_VAR_DPX": "bbw", "RPV_PRX_N_COA_DPX": "ly", "RPV_PRX_A_CSL_DPX": "ddy", "RPV_PRX_A_ASO_DPX": "ggy", "RPV_PRX_A_VAR_DPX": "bby", "RPV_PRX_A_COA_DPX": "xty", "RPV_PRX_M_CSL_DCT": "thw", "RPV_PRX_M_ASO_DCT": "khw", "RPV_PRX_M_VAR_DCT": "phw", "RPV_PRX_M_COA_DCT": "qhw", "RPV_PRX_U_CSL_DCT": "lty", "RPV_PRX_U_ASO_DCT": "lky", "RPV_PRX_U_VAR_DCT": "lpy", "RPV_PRX_U_COA_DCT": "ptw", "RPV_PRX_N_CSL_DCT": "ldw", "RPV_PRX_N_ASO_DCT": "lgw", "RPV_PRX_N_VAR_DCT": "lbw", "RPV_PRX_N_COA_DCT": "ry", "RPV_PRX_A_CSL_DCT": "ldy", "RPV_PRX_A_ASO_DCT": "lgy", "RPV_PRX_A_VAR_DCT": "lby", "RPV_PRX_A_COA_DCT": "ktw", "RPV_PRX_M_CSL_AGG": "t'w", "RPV_PRX_M_ASO_AGG": "k'w", "RPV_PRX_M_VAR_AGG": "p'w", "RPV_PRX_M_COA_AGG": "q'w", "RPV_PRX_U_CSL_AGG": "ţy", "RPV_PRX_U_ASO_AGG": "ży", "RPV_PRX_U_VAR_AGG": "fy", "RPV_PRX_U_COA_AGG": "mw", "RPV_PRX_N_CSL_AGG": "tv", "RPV_PRX_N_ASO_AGG": "kv", "RPV_PRX_N_VAR_AGG": "pv", "RPV_PRX_N_COA_AGG": "rw", "RPV_PRX_A_CSL_AGG": "dhy", "RPV_PRX_A_ASO_AGG": "jy", "RPV_PRX_A_VAR_AGG": "vy", "RPV_PRX_A_COA_AGG": "nw", "RPV_PRX_M_CSL_SEG": "tt'w", "RPV_PRX_M_ASO_SEG": "kk'w", "RPV_PRX_M_VAR_SEG": "pp'w", "RPV_PRX_M_COA_SEG": "qq'w", "RPV_PRX_U_CSL_SEG": "nty", "RPV_PRX_U_ASO_SEG": "ňky", "RPV_PRX_U_VAR_SEG": "npy", "RPV_PRX_U_COA_SEG": "ftw", "RPV_PRX_N_CSL_SEG": "ndw", "RPV_PRX_N_ASO_SEG": "ňgw", "RPV_PRX_N_VAR_SEG": "mbw", "RPV_PRX_N_COA_SEG": "ļw", "RPV_PRX_A_CSL_SEG": "ndy", "RPV_PRX_A_ASO_SEG": "ňgy", "RPV_PRX_A_VAR_SEG": "mby", "RPV_PRX_A_COA_SEG": "xtw", "RPV_PRX_M_CSL_CPN": "tthw", "RPV_PRX_M_ASO_CPN": "kkhw", "RPV_PRX_M_VAR_CPN": "pphw", "RPV_PRX_M_COA_CPN": "qqhw", "RPV_PRX_U_CSL_CPN": "řty", "RPV_PRX_U_ASO_CPN": "řky", "RPV_PRX_U_VAR_CPN": "řpy", "RPV_PRX_U_COA_CPN": "ptr", "RPV_PRX_N_CSL_CPN": "řdw", "RPV_PRX_N_ASO_CPN": "řgw", "RPV_PRX_N_VAR_CPN": "řbw", "RPV_PRX_N_COA_CPN": "řy", "RPV_PRX_A_CSL_CPN": "řdy", "RPV_PRX_A_ASO_CPN": "řgy", "RPV_PRX_A_VAR_CPN": "řby", "RPV_PRX_A_COA_CPN": "ktr", "RPV_PRX_M_CSL_COH": "ltw", "RPV_PRX_M_ASO_COH": "lkw", "RPV_PRX_M_VAR_COH": "lpw", "RPV_PRX_M_COA_COH": "lqw", "RPV_PRX_U_CSL_COH": "rty", "RPV_PRX_U_ASO_COH": "rky", "RPV_PRX_U_VAR_COH": "rpy", "RPV_PRX_U_COA_COH": "ftr", "RPV_PRX_N_CSL_COH": "bdw", "RPV_PRX_N_ASO_COH": "gdw", "RPV_PRX_N_VAR_COH": "dbw", "RPV_PRX_N_COA_COH": "tļw", "RPV_PRX_A_CSL_COH": "rdy", "RPV_PRX_A_ASO_COH": "rgy", "RPV_PRX_A_VAR_COH": "rby", "RPV_PRX_A_COA_COH": "xtr", "RPV_PRX_M_CSL_CST": "rtw", "RPV_PRX_M_ASO_CST": "rkw", "RPV_PRX_M_VAR_CST": "rpw", "RPV_PRX_M_COA_CST": "rqw", "RPV_PRX_U_CSL_CST": "pty", "RPV_PRX_U_ASO_CST": "kty", "RPV_PRX_U_VAR_CST": "tpy", "RPV_PRX_U_COA_CST": "pkw", "RPV_PRX_N_CSL_CST": "dgw", "RPV_PRX_N_ASO_CST": "gbw", "RPV_PRX_N_VAR_CST": "bgw", "RPV_PRX_N_COA_CST": "řw", "RPV_PRX_A_CSL_CST": "bdy", "RPV_PRX_A_ASO_CST": "gdy", "RPV_PRX_A_VAR_CST": "dby", "RPV_PRX_A_COA_CST": "tkw", "RPV_PRX_M_CSL_MLT": "ntw", "RPV_PRX_M_ASO_MLT": "ňkw", "RPV_PRX_M_VAR_MLT": "mpw", "RPV_PRX_M_COA_MLT": "ňqw", "RPV_PRX_U_CSL_MLT": "tky", "RPV_PRX_U_ASO_MLT": "kpy", "RPV_PRX_U_VAR_MLT": "pky", "RPV_PRX_U_COA_MLT": "fkw", "RPV_PRX_N_CSL_MLT": "rdw", "RPV_PRX_N_ASO_MLT": "rgw", "RPV_PRX_N_VAR_MLT": "rbw", "RPV_PRX_N_COA_MLT": "lř", "RPV_PRX_A_CSL_MLT": "dgy", "RPV_PRX_A_ASO_MLT": "gby", "RPV_PRX_A_VAR_MLT": "bgy", "RPV_PRX_A_COA_MLT": "ţkw", "RPV_ICP_M_CSL_UNI": "tl", "RPV_ICP_M_ASO_UNI": "kl", "RPV_ICP_M_VAR_UNI": "pl", "RPV_ICP_M_COA_UNI": "ql", "RPV_ICP_U_CSL_UNI": "dl", "RPV_ICP_U_ASO_UNI": "gl", "RPV_ICP_U_VAR_UNI": "bl", "RPV_ICP_U_COA_UNI": "ml", "RPV_ICP_N_CSL_UNI": "skl", "RPV_ICP_N_ASO_UNI": "stl", "RPV_ICP_N_VAR_UNI": "spl", "RPV_ICP_N_COA_UNI": "sql", "RPV_ICP_A_CSL_UNI": "škl", "RPV_ICP_A_ASO_UNI": "štl", "RPV_ICP_A_VAR_UNI": "špl", "RPV_ICP_A_COA_UNI": "šql", "RPV_ICP_M_CSL_DPX": "ttl", "RPV_ICP_M_ASO_DPX": "kkl", "RPV_ICP_M_VAR_DPX": "ppl", "RPV_ICP_M_COA_DPX": "qql", "RPV_ICP_U_CSL_DPX": "ddl", "RPV_ICP_U_ASO_DPX": "ggl", "RPV_ICP_U_VAR_DPX": "bbl", "RPV_ICP_U_COA_DPX": "mř", "RPV_ICP_N_CSL_DPX": "ckl", "RPV_ICP_N_ASO_DPX": "ctl", "RPV_ICP_N_VAR_DPX": "cpl", "RPV_ICP_N_COA_DPX": "cql", "RPV_ICP_A_CSL_DPX": "čkl", "RPV_ICP_A_ASO_DPX": "čtl", "RPV_ICP_A_VAR_DPX": "čpl", "RPV_ICP_A_COA_DPX": "čql", "RPV_ICP_M_CSL_DCT": "ltl", "RPV_ICP_M_ASO_DCT": "lkl", "RPV_ICP_M_VAR_DCT": "lpl", "RPV_ICP_M_COA_DCT": "lql", "RPV_ICP_U_CSL_DCT": "ldl", "RPV_ICP_U_ASO_DCT": "lgl", "RPV_ICP_U_VAR_DCT": "lbl", "RPV_ICP_U_COA_DCT": "ňl", "RPV_ICP_N_CSL_DCT": "ckw", "RPV_ICP_N_ASO_DCT": "ctw", "RPV_ICP_N_VAR_DCT": "cpw", "RPV_ICP_N_COA_DCT": "cqw", "RPV_ICP_A_CSL_DCT": "čkw", "RPV_ICP_A_ASO_DCT": "čtw", "RPV_ICP_A_VAR_DCT": "čpw", "RPV_ICP_A_COA_DCT": "čqw", "RPV_ICP_M_CSL_AGG": "rtl", "RPV_ICP_M_ASO_AGG": "rkl", "RPV_ICP_M_VAR_AGG": "rpl", "RPV_ICP_M_COA_AGG": "rql", "RPV_ICP_U_CSL_AGG": "rdl", "RPV_ICP_U_ASO_AGG": "rgl", "RPV_ICP_U_VAR_AGG": "rbl", "RPV_ICP_U_COA_AGG": "nl", "RPV_ICP_N_CSL_AGG": "skw", "RPV_ICP_N_ASO_AGG": "stw", "RPV_ICP_N_VAR_AGG": "spw", "RPV_ICP_N_COA_AGG": "sqw", "RPV_ICP_A_CSL_AGG": "škw", "RPV_ICP_A_ASO_AGG": "štw", "RPV_ICP_A_VAR_AGG": "špw", "RPV_ICP_A_COA_AGG": "šqw", "RPV_ICP_M_CSL_SEG": "ntl", "RPV_ICP_M_ASO_SEG": "ňkl", "RPV_ICP_M_VAR_SEG": "mpl", "RPV_ICP_M_COA_SEG": "ňql", "RPV_ICP_U_CSL_SEG": "ndl", "RPV_ICP_U_ASO_SEG": "ňgl", "RPV_ICP_U_VAR_SEG": "mbl", "RPV_ICP_U_COA_SEG": "ţř", "RPV_ICP_N_CSL_SEG": "sskw", "RPV_ICP_N_ASO_SEG": "sstw", "RPV_ICP_N_VAR_SEG": "sspw", "RPV_ICP_N_COA_SEG": "ssqw", "RPV_ICP_A_CSL_SEG": "šškw", "RPV_ICP_A_ASO_SEG": "šštw", "RPV_ICP_A_VAR_SEG": "ššpw", "RPV_ICP_A_COA_SEG": "ššqw", "RPV_ICP_M_CSL_CPN": "řtl", "RPV_ICP_M_ASO_CPN": "řkl", "RPV_ICP_M_VAR_CPN": "řpl", "RPV_ICP_M_COA_CPN": "řql", "RPV_ICP_U_CSL_CPN": "řdl", "RPV_ICP_U_ASO_CPN": "řgl", "RPV_ICP_U_VAR_CPN": "řbl", "RPV_ICP_U_COA_CPN": "fř", "RPV_ICP_N_CSL_CPN": "çkw", "RPV_ICP_N_ASO_CPN": "çtw", "RPV_ICP_N_VAR_CPN": "çpw", "RPV_ICP_N_COA_CPN": "çqw", "RPV_ICP_A_CSL_CPN": "xxw", "RPV_ICP_A_ASO_CPN": "ţţw", "RPV_ICP_A_VAR_CPN": "ffw", "RPV_ICP_A_COA_CPN": "xxhw", "RPV_ICP_M_CSL_COH": "mtl", "RPV_ICP_M_ASO_COH": "mkl", "RPV_ICP_M_VAR_COH": "ňpl", "RPV_ICP_M_COA_COH": "mql", "RPV_ICP_U_CSL_COH": "bdl", "RPV_ICP_U_ASO_COH": "gdl", "RPV_ICP_U_VAR_COH": "dbl", "RPV_ICP_U_COA_COH": "př", "RPV_ICP_N_CSL_COH": "sk'w", "RPV_ICP_N_ASO_COH": "st'w", "RPV_ICP_N_VAR_COH": "sp'w", "RPV_ICP_N_COA_COH": "sq'w", "RPV_ICP_A_CSL_COH": "šk'w", "RPV_ICP_A_ASO_COH": "št'w", "RPV_ICP_A_VAR_COH": "šp'w", "RPV_ICP_A_COA_COH": "šq'w", "RPV_ICP_M_CSL_CST": "ļtl", "RPV_ICP_M_ASO_CST": "ļkl", "RPV_ICP_M_VAR_CST": "ļpl", "RPV_ICP_M_COA_CST": "ļql", "RPV_ICP_U_CSL_CST": "dgl", "RPV_ICP_U_ASO_CST": "gbl", "RPV_ICP_U_VAR_CST": "bgl", "RPV_ICP_U_COA_CST": "tř", "RPV_ICP_N_CSL_CST": "ck'w", "RPV_ICP_N_ASO_CST": "ct'w", "RPV_ICP_N_VAR_CST": "cp'w", "RPV_ICP_N_COA_CST": "cq'w", "RPV_ICP_A_CSL_CST": "čk'w", "RPV_ICP_A_ASO_CST": "čt'w", "RPV_ICP_A_VAR_CST": "čp'w", "RPV_ICP_A_COA_CST": "čq'w", "RPV_ICP_M_CSL_MLT": "kçw", "RPV_ICP_M_ASO_MLT": "c'w", "RPV_ICP_M_VAR_MLT": "tfw", "RPV_ICP_M_COA_MLT": "č'w", "RPV_ICP_U_CSL_MLT": "vbl", "RPV_ICP_U_ASO_MLT": "vgl", "RPV_ICP_U_VAR_MLT": "vdl", "RPV_ICP_U_COA_MLT": "lr", "RPV_ICP_N_CSL_MLT": "sskl", "RPV_ICP_N_ASO_MLT": "sstl", "RPV_ICP_N_VAR_MLT": "sspl", "RPV_ICP_N_COA_MLT": "ssql", "RPV_ICP_A_CSL_MLT": "šškl", "RPV_ICP_A_ASO_MLT": "šštl", "RPV_ICP_A_VAR_MLT": "ššpl", "RPV_ICP_A_COA_MLT": "ššql", "RPV_TRM_M_CSL_UNI": "tr", "RPV_TRM_M_ASO_UNI": "kr", "RPV_TRM_M_VAR_UNI": "pr", "RPV_TRM_M_COA_UNI": "qr", "RPV_TRM_U_CSL_UNI": "dr", "RPV_TRM_U_ASO_UNI": "gr", "RPV_TRM_U_VAR_UNI": "br", "RPV_TRM_U_COA_UNI": "mr", "RPV_TRM_N_CSL_UNI": "skr", "RPV_TRM_N_ASO_UNI": "str", "RPV_TRM_N_VAR_UNI": "spr", "RPV_TRM_N_COA_UNI": "sqr", "RPV_TRM_A_CSL_UNI": "škr", "RPV_TRM_A_ASO_UNI": "štr", "RPV_TRM_A_VAR_UNI": "špr", "RPV_TRM_A_COA_UNI": "šqr", "RPV_TRM_M_CSL_DPX": "ttr", "RPV_TRM_M_ASO_DPX": "kkr", "RPV_TRM_M_VAR_DPX": "ppr", "RPV_TRM_M_COA_DPX": "qqr", "RPV_TRM_U_CSL_DPX": "ddr", "RPV_TRM_U_ASO_DPX": "ggr", "RPV_TRM_U_VAR_DPX": "bbr", "RPV_TRM_U_COA_DPX": "nř", "RPV_TRM_N_CSL_DPX": "ckr", "RPV_TRM_N_ASO_DPX": "ctr", "RPV_TRM_N_VAR_DPX": "cpr", "RPV_TRM_N_COA_DPX": "cqr", "RPV_TRM_A_CSL_DPX": "čkr", "RPV_TRM_A_ASO_DPX": "čtr", "RPV_TRM_A_VAR_DPX": "čpr", "RPV_TRM_A_COA_DPX": "čqr", "RPV_TRM_M_CSL_DCT": "ltr", "RPV_TRM_M_ASO_DCT": "lkr", "RPV_TRM_M_VAR_DCT": "lpr", "RPV_TRM_M_COA_DCT": "lqr", "RPV_TRM_U_CSL_DCT": "ldr", "RPV_TRM_U_ASO_DCT": "lgr", "RPV_TRM_U_VAR_DCT": "lbr", "RPV_TRM_U_COA_DCT": "ňr", "RPV_TRM_N_CSL_DCT": "cky", "RPV_TRM_N_ASO_DCT": "cty", "RPV_TRM_N_VAR_DCT": "cpy", "RPV_TRM_N_COA_DCT": "c'y", "RPV_TRM_A_CSL_DCT": "čky", "RPV_TRM_A_ASO_DCT": "čty", "RPV_TRM_A_VAR_DCT": "čpy", "RPV_TRM_A_COA_DCT": "č'y", "RPV_TRM_M_CSL_AGG": "rtr", "RPV_TRM_M_ASO_AGG": "rkr", "RPV_TRM_M_VAR_AGG": "rpr", "RPV_TRM_M_COA_AGG": "rqr", "RPV_TRM_U_CSL_AGG": "rdr", "RPV_TRM_U_ASO_AGG": "rgr", "RPV_TRM_U_VAR_AGG": "rbr", "RPV_TRM_U_COA_AGG": "nr", "RPV_TRM_N_CSL_AGG": "sky", "RPV_TRM_N_ASO_AGG": "sty", "RPV_TRM_N_VAR_AGG": "spy", "RPV_TRM_N_COA_AGG": "cy", "RPV_TRM_A_CSL_AGG": "šky", "RPV_TRM_A_ASO_AGG": "šty", "RPV_TRM_A_VAR_AGG": "špy", "RPV_TRM_A_COA_AGG": "čy", "RPV_TRM_M_CSL_SEG": "ntr", "RPV_TRM_M_ASO_SEG": "ňkr", "RPV_TRM_M_VAR_SEG": "mpr", "RPV_TRM_M_COA_SEG": "ňqr", "RPV_TRM_U_CSL_SEG": "ndr", "RPV_TRM_U_ASO_SEG": "ňgr", "RPV_TRM_U_VAR_SEG": "mbr", "RPV_TRM_U_COA_SEG": "dhř", "RPV_TRM_N_CSL_SEG": "ssky", "RPV_TRM_N_ASO_SEG": "ssty", "RPV_TRM_N_VAR_SEG": "sspy", "RPV_TRM_N_COA_SEG": "çr", "RPV_TRM_A_CSL_SEG": "ššky", "RPV_TRM_A_ASO_SEG": "ššty", "RPV_TRM_A_VAR_SEG": "ššpy", "RPV_TRM_A_COA_SEG": "çř", "RPV_TRM_M_CSL_CPN": "řtr", "RPV_TRM_M_ASO_CPN": "řkr", "RPV_TRM_M_VAR_CPN": "řpr", "RPV_TRM_M_COA_CPN": "řqr", "RPV_TRM_U_CSL_CPN": "řdr", "RPV_TRM_U_ASO_CPN": "řgr", "RPV_TRM_U_VAR_CPN": "řbr", "RPV_TRM_U_COA_CPN": "vř", "RPV_TRM_N_CSL_CPN": "čhw", "RPV_TRM_N_ASO_CPN": "chy", "RPV_TRM_N_VAR_CPN": "chw", "RPV_TRM_N_COA_CPN": "čhy", "RPV_TRM_A_CSL_CPN": "ļkw", "RPV_TRM_A_ASO_CPN": "ļtw", "RPV_TRM_A_VAR_CPN": "ļpw", "RPV_TRM_A_COA_CPN": "ļqw", "RPV_TRM_M_CSL_COH": "mtr", "RPV_TRM_M_ASO_COH": "mkr", "RPV_TRM_M_VAR_COH": "ňpr", "RPV_TRM_M_COA_COH": "mqr", "RPV_TRM_U_CSL_COH": "bdr", "RPV_TRM_U_ASO_COH": "gdr", "RPV_TRM_U_VAR_COH": "dbr", "RPV_TRM_U_COA_COH": "bř", "RPV_TRM_N_CSL_COH": "skhw", "RPV_TRM_N_ASO_COH": "sthw", "RPV_TRM_N_VAR_COH": "sphw", "RPV_TRM_N_COA_COH": "sqhw", "RPV_TRM_A_CSL_COH": "škhw", "RPV_TRM_A_ASO_COH": "šthw", "RPV_TRM_A_VAR_COH": "šphw", "RPV_TRM_A_COA_COH": "šqhw", "RPV_TRM_M_CSL_CST": "ļtr", "RPV_TRM_M_ASO_CST": "ļkr", "RPV_TRM_M_VAR_CST": "ļpr", "RPV_TRM_M_COA_CST": "ļqr", "RPV_TRM_U_CSL_CST": "dgr", "RPV_TRM_U_ASO_CST": "gbr", "RPV_TRM_U_VAR_CST": "bgr", "RPV_TRM_U_COA_CST": "dř", "RPV_TRM_N_CSL_CST": "ckhw", "RPV_TRM_N_ASO_CST": "cthw", "RPV_TRM_N_VAR_CST": "cphw", "RPV_TRM_N_COA_CST": "cqhw", "RPV_TRM_A_CSL_CST": "čkhw", "RPV_TRM_A_ASO_CST": "čthw", "RPV_TRM_A_VAR_CST": "čphw", "RPV_TRM_A_COA_CST": "čqhw", "RPV_TRM_M_CSL_MLT": "rtn", "RPV_TRM_M_ASO_MLT": "rkn", "RPV_TRM_M_VAR_MLT": "rpn", "RPV_TRM_M_COA_MLT": "rqn", "RPV_TRM_U_CSL_MLT": "vbr", "RPV_TRM_U_ASO_MLT": "vgr", "RPV_TRM_U_VAR_MLT": "vdr", "RPV_TRM_U_COA_MLT": "gř", "RPV_TRM_N_CSL_MLT": "sskr", "RPV_TRM_N_ASO_MLT": "sstr", "RPV_TRM_N_VAR_MLT": "sspr", "RPV_TRM_N_COA_MLT": "ssqr", "RPV_TRM_A_CSL_MLT": "šškr", "RPV_TRM_A_ASO_MLT": "šštr", "RPV_TRM_A_VAR_MLT": "ššpr", "RPV_TRM_A_COA_MLT": "ššqr", "RPV_DPL_M_CSL_UNI": "sl", "RPV_DPL_M_ASO_UNI": "šl", "RPV_DPL_M_VAR_UNI": "zl", "RPV_DPL_M_COA_UNI": "žl", "RPV_DPL_U_CSL_UNI": "fl", "RPV_DPL_U_ASO_UNI": "ţl", "RPV_DPL_U_VAR_UNI": "xl", "RPV_DPL_U_COA_UNI": "xhl", "RPV_DPL_N_CSL_UNI": "vl", "RPV_DPL_N_ASO_UNI": "dhl", "RPV_DPL_N_VAR_UNI": "sv", "RPV_DPL_N_COA_UNI": "zv", "RPV_DPL_A_CSL_UNI": "sm", "RPV_DPL_A_ASO_UNI": "šm", "RPV_DPL_A_VAR_UNI": "sn", "RPV_DPL_A_COA_UNI": "šn", "RPV_DPL_M_CSL_DPX": "ssl", "RPV_DPL_M_ASO_DPX": "ššl", "RPV_DPL_M_VAR_DPX": "zzl", "RPV_DPL_M_COA_DPX": "žžl", "RPV_DPL_U_CSL_DPX": "ffl", "RPV_DPL_U_ASO_DPX": "ţţl", "RPV_DPL_U_VAR_DPX": "xxl", "RPV_DPL_U_COA_DPX": "xxhl", "RPV_DPL_N_CSL_DPX": "vvl", "RPV_DPL_N_ASO_DPX": "ddhl", "RPV_DPL_N_VAR_DPX": "sř", "RPV_DPL_N_COA_DPX": "zř", "RPV_DPL_A_CSL_DPX": "sy", "RPV_DPL_A_ASO_DPX": "šy", "RPV_DPL_A_VAR_DPX": "zy", "RPV_DPL_A_COA_DPX": "žy", "RPV_DPL_M_CSL_DCT": "lsl", "RPV_DPL_M_ASO_DCT": "lšl", "RPV_DPL_M_VAR_DCT": "lzl", "RPV_DPL_M_COA_DCT": "lžl", "RPV_DPL_U_CSL_DCT": "lfl", "RPV_DPL_U_ASO_DCT": "lţl", "RPV_DPL_U_VAR_DCT": "lxl", "RPV_DPL_U_COA_DCT": "lxhl", "RPV_DPL_N_CSL_DCT": "lvl", "RPV_DPL_N_ASO_DCT": "ldhl", "RPV_DPL_N_VAR_DCT": "ksw", "RPV_DPL_N_COA_DCT": "psw", "RPV_DPL_A_CSL_DCT": "cm", "RPV_DPL_A_ASO_DCT": "čm", "RPV_DPL_A_VAR_DCT": "cn", "RPV_DPL_A_COA_DCT": "čn", "RPV_DPL_M_CSL_AGG": "rsl", "RPV_DPL_M_ASO_AGG": "ršl", "RPV_DPL_M_VAR_AGG": "rzl", "RPV_DPL_M_COA_AGG": "ržl", "RPV_DPL_U_CSL_AGG": "rfl", "RPV_DPL_U_ASO_AGG": "rţl", "RPV_DPL_U_VAR_AGG": "rxl", "RPV_DPL_U_COA_AGG": "rxhl", "RPV_DPL_N_CSL_AGG": "rvl", "RPV_DPL_N_ASO_AGG": "rdhl", "RPV_DPL_N_VAR_AGG": "sxw", "RPV_DPL_N_COA_AGG": "sxhw", "RPV_DPL_A_CSL_AGG": "zm", "RPV_DPL_A_ASO_AGG": "žm", "RPV_DPL_A_VAR_AGG": "zn", "RPV_DPL_A_COA_AGG": "žn", "RPV_DPL_M_CSL_SEG": "msl", "RPV_DPL_M_ASO_SEG": "mšl", "RPV_DPL_M_VAR_SEG": "mzl", "RPV_DPL_M_COA_SEG": "mžl", "RPV_DPL_U_CSL_SEG": "mfl", "RPV_DPL_U_ASO_SEG": "nţl", "RPV_DPL_U_VAR_SEG": "ňxl", "RPV_DPL_U_COA_SEG": "ňxhl", "RPV_DPL_N_CSL_SEG": "mvl", "RPV_DPL_N_ASO_SEG": "ndhl", "RPV_DPL_N_VAR_SEG": "lsř", "RPV_DPL_N_COA_SEG": "lzř", "RPV_DPL_A_CSL_SEG": "żm", "RPV_DPL_A_ASO_SEG": "jm", "RPV_DPL_A_VAR_SEG": "żn", "RPV_DPL_A_COA_SEG": "jn", "RPV_DPL_M_CSL_CPN": "řsl", "RPV_DPL_M_ASO_CPN": "řšl", "RPV_DPL_M_VAR_CPN": "řzl", "RPV_DPL_M_COA_CPN": "řžl", "RPV_DPL_U_CSL_CPN": "řfl", "RPV_DPL_U_ASO_CPN": "řţl", "RPV_DPL_U_VAR_CPN": "řxl", "RPV_DPL_U_COA_CPN": "qtl", "RPV_DPL_N_CSL_CPN": "řvl", "RPV_DPL_N_ASO_CPN": "řdhl", "RPV_DPL_N_VAR_CPN": "rsř", "RPV_DPL_N_COA_CPN": "rzř", "RPV_DPL_A_CSL_CPN": "çm", "RPV_DPL_A_ASO_CPN": "ļm", "RPV_DPL_A_VAR_CPN": "çn", "RPV_DPL_A_COA_CPN": "ļn", "RPV_DPL_M_CSL_COH": "nsl", "RPV_DPL_M_ASO_COH": "nšl", "RPV_DPL_M_VAR_COH": "nzl", "RPV_DPL_M_COA_COH": "nžl", "RPV_DPL_U_CSL_COH": "fxl", "RPV_DPL_U_ASO_COH": "ţxl", "RPV_DPL_U_VAR_COH": "xfl", "RPV_DPL_U_COA_COH": "xhfl", "RPV_DPL_N_CSL_COH": "lpţ", "RPV_DPL_N_ASO_COH": "cl", "RPV_DPL_N_VAR_COH": "fsw", "RPV_DPL_N_COA_COH": "sfw", "RPV_DPL_A_CSL_COH": "bm", "RPV_DPL_A_ASO_COH": "vm", "RPV_DPL_A_VAR_COH": "bn", "RPV_DPL_A_COA_COH": "vn", "RPV_DPL_M_CSL_CST": "ňsl", "RPV_DPL_M_ASO_CST": "ňšl", "RPV_DPL_M_VAR_CST": "ňzl", "RPV_DPL_M_COA_CST": "ňžl", "RPV_DPL_U_CSL_CST": "ňfl", "RPV_DPL_U_ASO_CST": "mţl", "RPV_DPL_U_VAR_CST": "mxl", "RPV_DPL_U_COA_CST": "mxhl", "RPV_DPL_N_CSL_CST": "lkţ", "RPV_DPL_N_ASO_CST": "čl", "RPV_DPL_N_VAR_CST": "řsř", "RPV_DPL_N_COA_CST": "řzř", "RPV_DPL_A_CSL_CST": "dm", "RPV_DPL_A_ASO_CST": "dhm", "RPV_DPL_A_VAR_CST": "dn", "RPV_DPL_A_COA_CST": "dhn", "RPV_DPL_M_CSL_MLT": "ţst", "RPV_DPL_M_ASO_MLT": "ţšt", "RPV_DPL_M_VAR_MLT": "ţsp", "RPV_DPL_M_COA_MLT": "ţšp", "RPV_DPL_U_CSL_MLT": "pxl", "RPV_DPL_U_ASO_MLT": "txl", "RPV_DPL_U_VAR_MLT": "xţl", "RPV_DPL_U_COA_MLT": "xhţl", "RPV_DPL_N_CSL_MLT": "mpļ", "RPV_DPL_N_ASO_MLT": "ntļ", "RPV_DPL_N_VAR_MLT": "bzw", "RPV_DPL_N_COA_MLT": "gzw", "RPV_DPL_A_CSL_MLT": "gm", "RPV_DPL_A_ASO_MLT": "kř", "RPV_DPL_A_VAR_MLT": "gn", "RPV_DPL_A_COA_MLT": "ňř", "RPV_GRA_M_CSL_UNI": "sr", "RPV_GRA_M_ASO_UNI": "šr", "RPV_GRA_M_VAR_UNI": "zr", "RPV_GRA_M_COA_UNI": "žr", "RPV_GRA_U_CSL_UNI": "fr", "RPV_GRA_U_ASO_UNI": "ţr", "RPV_GRA_U_VAR_UNI": "xr", "RPV_GRA_U_COA_UNI": "xhr", "RPV_GRA_N_CSL_UNI": "vr", "RPV_GRA_N_ASO_UNI": "dhr", "RPV_GRA_N_VAR_UNI": "šv", "RPV_GRA_N_COA_UNI": "žv", "RPV_GRA_A_CSL_UNI": "tm", "RPV_GRA_A_ASO_UNI": "km", "RPV_GRA_A_VAR_UNI": "pm", "RPV_GRA_A_COA_UNI": "qm", "RPV_GRA_M_CSL_DPX": "ssr", "RPV_GRA_M_ASO_DPX": "ššr", "RPV_GRA_M_VAR_DPX": "zzr", "RPV_GRA_M_COA_DPX": "žžr", "RPV_GRA_U_CSL_DPX": "ffr", "RPV_GRA_U_ASO_DPX": "ţţr", "RPV_GRA_U_VAR_DPX": "xxr", "RPV_GRA_U_COA_DPX": "xxhr", "RPV_GRA_N_CSL_DPX": "vvr", "RPV_GRA_N_ASO_DPX": "ddhr", "RPV_GRA_N_VAR_DPX": "šř", "RPV_GRA_N_COA_DPX": "žř", "RPV_GRA_A_CSL_DPX": "ţm", "RPV_GRA_A_ASO_DPX": "xm", "RPV_GRA_A_VAR_DPX": "fm", "RPV_GRA_A_COA_DPX": "xhm", "RPV_GRA_M_CSL_DCT": "lsr", "RPV_GRA_M_ASO_DCT": "lšr", "RPV_GRA_M_VAR_DCT": "lzr", "RPV_GRA_M_COA_DCT": "lžr", "RPV_GRA_U_CSL_DCT": "lfr", "RPV_GRA_U_ASO_DCT": "lţr", "RPV_GRA_U_VAR_DCT": "lxr", "RPV_GRA_U_COA_DCT": "lxhr", "RPV_GRA_N_CSL_DCT": "lvr", "RPV_GRA_N_ASO_DCT": "ldhr", "RPV_GRA_N_VAR_DCT": "kšw", "RPV_GRA_N_COA_DCT": "pšw", "RPV_GRA_A_CSL_DCT": "ţn", "RPV_GRA_A_ASO_DCT": "xn", "RPV_GRA_A_VAR_DCT": "fn", "RPV_GRA_A_COA_DCT": "xhn", "RPV_GRA_M_CSL_AGG": "rsr", "RPV_GRA_M_ASO_AGG": "ršr", "RPV_GRA_M_VAR_AGG": "rzr", "RPV_GRA_M_COA_AGG": "ržr", "RPV_GRA_U_CSL_AGG": "rfr", "RPV_GRA_U_ASO_AGG": "rţr", "RPV_GRA_U_VAR_AGG": "rxr", "RPV_GRA_U_COA_AGG": "rxhr", "RPV_GRA_N_CSL_AGG": "rvr", "RPV_GRA_N_ASO_AGG": "rdhr", "RPV_GRA_N_VAR_AGG": "šxw", "RPV_GRA_N_COA_AGG": "šxhw", "RPV_GRA_A_CSL_AGG": "tn", "RPV_GRA_A_ASO_AGG": "kn", "RPV_GRA_A_VAR_AGG": "pn", "RPV_GRA_A_COA_AGG": "qn", "RPV_GRA_M_CSL_SEG": "msr", "RPV_GRA_M_ASO_SEG": "mšr", "RPV_GRA_M_VAR_SEG": "mzr", "RPV_GRA_M_COA_SEG": "mžr", "RPV_GRA_U_CSL_SEG": "mfr", "RPV_GRA_U_ASO_SEG": "nţr", "RPV_GRA_U_VAR_SEG": "ňxr", "RPV_GRA_U_COA_SEG": "ňxhr", "RPV_GRA_N_CSL_SEG": "mvr", "RPV_GRA_N_ASO_SEG": "ndhr", "RPV_GRA_N_VAR_SEG": "lšř", "RPV_GRA_N_COA_SEG": "lžř", "RPV_GRA_A_CSL_SEG": "rsm", "RPV_GRA_A_ASO_SEG": "rzm", "RPV_GRA_A_VAR_SEG": "ršm", "RPV_GRA_A_COA_SEG": "ržm", "RPV_GRA_M_CSL_CPN": "řsr", "RPV_GRA_M_ASO_CPN": "řšr", "RPV_GRA_M_VAR_CPN": "řzr", "RPV_GRA_M_COA_CPN": "řžr", "RPV_GRA_U_CSL_CPN": "řfr", "RPV_GRA_U_ASO_CPN": "řţr", "RPV_GRA_U_VAR_CPN": "řxr", "RPV_GRA_U_COA_CPN": "qtr", "RPV_GRA_N_CSL_CPN": "řvr", "RPV_GRA_N_ASO_CPN": "řdhr", "RPV_GRA_N_VAR_CPN": "ršř", "RPV_GRA_N_COA_CPN": "ržř", "RPV_GRA_A_CSL_CPN": "rsn", "RPV_GRA_A_ASO_CPN": "rzn", "RPV_GRA_A_VAR_CPN": "ršn", "RPV_GRA_A_COA_CPN": "ržn", "RPV_GRA_M_CSL_COH": "nsr", "RPV_GRA_M_ASO_COH": "nšr", "RPV_GRA_M_VAR_COH": "nzr", "RPV_GRA_M_COA_COH": "nžr", "RPV_GRA_U_CSL_COH": "fxr", "RPV_GRA_U_ASO_COH": "ţxr", "RPV_GRA_U_VAR_COH": "xfr", "RPV_GRA_U_COA_COH": "xhfr", "RPV_GRA_N_CSL_COH": "rpţ", "RPV_GRA_N_ASO_COH": "cr", "RPV_GRA_N_VAR_COH": "fšw", "RPV_GRA_N_COA_COH": "šfw", "RPV_GRA_A_CSL_COH": "sň", "RPV_GRA_A_ASO_COH": "zň", "RPV_GRA_A_VAR_COH": "šň", "RPV_GRA_A_COA_COH": "žň", "RPV_GRA_M_CSL_CST": "ňsr", "RPV_GRA_M_ASO_CST": "ňšr", "RPV_GRA_M_VAR_CST": "ňzr", "RPV_GRA_M_COA_CST": "ňžr", "RPV_GRA_U_CSL_CST": "ňfr", "RPV_GRA_U_ASO_CST": "mţr", "RPV_GRA_U_VAR_CST": "mxr", "RPV_GRA_U_COA_CST": "mxhr", "RPV_GRA_N_CSL_CST": "rkţ", "RPV_GRA_N_ASO_CST": "čr", "RPV_GRA_N_VAR_CST": "řšř", "RPV_GRA_N_COA_CST": "řžř", "RPV_GRA_A_CSL_CST": "rsň", "RPV_GRA_A_ASO_CST": "rzň", "RPV_GRA_A_VAR_CST": "ršň", "RPV_GRA_A_COA_CST": "ržň", "RPV_GRA_M_CSL_MLT": "ţsk", "RPV_GRA_M_ASO_MLT": "ţšk", "RPV_GRA_M_VAR_MLT": "ţsq", "RPV_GRA_M_COA_MLT": "ţšq", "RPV_GRA_U_CSL_MLT": "pxr", "RPV_GRA_U_ASO_MLT": "txr", "RPV_GRA_U_VAR_MLT": "xţr", "RPV_GRA_U_COA_MLT": "xhţr", "RPV_GRA_N_CSL_MLT": "mpř", "RPV_GRA_N_ASO_MLT": "ntř", "RPV_GRA_N_VAR_MLT": "bžw", "RPV_GRA_N_COA_MLT": "gžw", "RPV_GRA_A_CSL_MLT": "nm", "RPV_GRA_A_ASO_MLT": "ňm", "RPV_GRA_A_VAR_MLT": "mn", "RPV_GRA_A_COA_MLT": "ňn" }
